##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role generates value files for various k8 components
#############################################################################################

# Ensure that the directory exists for each entity, if not, it creates them
- name: Ensure {{ component_type_name }} dir exists
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/directory"
  vars:
    path: "{{ release_dir }}/{{ component_type_name }}"

# Create the value file for the k8 components
- name: "Create {{ component_type }} file for {{ component_type_name }}"
  template:
    src: "{{ k8_templates[type] | default('default.tpl') }}"
    dest: "{{ values_file }}"
  vars:
    values_file: "{{ release_dir }}/{{ component_type_name }}/{{ component_type }}.yaml"
    type: "{{ component_type }}"
