##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"

default:
  version: "1.23.0"
  os: "linux"    # use "darwin" for MacOS X, "windows" for Windows
  arch: "amd64"  # other possible values: "386","arm64","arm","ppc64le","s390x"
  bin_directory: "~/bin"  
  checksum: ""
