##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v2
name: fabric-cacti-connector
description: "Hyperledger Fabric: Deploys Cactus Fabric Connector."
type: application
version: '0.15.0'
# For Cactus release 1.1.3
appVersion: "1.1.3"
