apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: calv-net-ca
  namespace: calv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: calv-net-ca
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: feature-614
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: calv-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: calv-admin
    storage:
      storageclassname: calvsc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: calv-net-auth
      secretcert: secret/crypto/peerOrganizations/calv-net/ca?ca.calv-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/calv-net/ca?calv-net-CA.key
      secretadminpass: secret/credentials/calv-net/ca/calv?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com
