##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
- name: "Create ConfigMaps Using Scripts"
  kubernetes.core.helm:
    name: bevel-script
    chart_ref: "{{ playbook_dir }}/../../shared/charts/bevel-scripts"
    release_namespace: "{{ namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubernetes.config_file }}"
    values:
      network_type: "{{ network_type }}"
      namespace: "{{ namespace }}"
