##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v2
name: letsencrypt-issuer
description: "Create clusterissuer for letsencrypt"
type: application
version: '0.15.1'
