##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Delete the previously created release file
- name: Delete release file {{ pod_name }}
  file:
    path: "{{ file_path }}"
    state: absent

# Git Push : Push the previously deleted value file
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ gitops_value }}"
    msg: "[ci skip] Deleting the previously created {{ pod_name }} value file"

# Delete the previously created HelmRelease
- name: Delete the previous {{ pod_name }} HelmRelease
  k8s:
    api_version: "helm.toolkit.fluxcd.io/v2beta1"
    kind: HelmRelease
    name: "{{ hr_name }}"
    namespace: "{{ component_ns }}"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
