##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-config-{{ include "bevel-vault-mgmt.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: policies-config
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
data:
  policies-config.json: |-
    {{ if eq .Values.global.vault.network "besu" -}}
    {
      "policy": 
        "path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/*\" {
          capabilities = [\"list\", \"read\", \"create\", \"update\"]
        }
        path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/smartContracts/*\" {
          capabilities = [\"list\", \"read\"]
        }"
    }
    {{ end }}
    {{ if eq .Values.global.vault.network "corda" -}}
    {
      "policy": 
        "path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/*\" {
          capabilities = [\"list\", \"read\", \"create\", \"update\"]
        }"
    }
    {{ end }}
    {{ if eq .Values.global.vault.network "fabric" -}}
    {
      "policy": 
        "path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/*\" {
          capabilities = [\"list\", \"read\", \"create\", \"update\"]
        }
        path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/credentials/*\" {
          capabilities = [\"list\", \"read\", \"create\", \"update\"]
        }"
    }
    {{ end }}
    {{ if eq .Values.global.vault.network "quorum" -}}
    {
      "policy": 
        "path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/crypto/*\" {
          capabilities = [\"list\", \"read\", \"create\", \"update\"]
        }
        path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/smartContracts/*\" {
          capabilities = [\"list\", \"read\"]
        }"
    }
    {{ end }}
    {{ if eq .Values.global.vault.network "corda-ent" -}}
    {
      "policy": 
        "path \"{{ .Values.global.vault.secretEngine }}/{{ .Values.global.vault.secretPrefix }}/*\" {
          capabilities = [\"list\", \"read\", \"create\", \"update\"]
        }"
    }
    {{ end }}
