#############################################################################################
# This role saves the crypto from Vault into ansible_provisioner
#############################################################################################

# Ensure admincerts directory is present in build
- name: Ensure directory exists
  file:
    path: "{{ cert_path }}"
    state: directory

# Save the cert file
- name: Save cert
  local_action: copy content="{{ vault_output['data'].ambassadorcrt | b64decode }}" dest="{{ cert_path }}/ambassador.crt"
  when: type == "ambassador"
# Save the key file
- name: Save key
  local_action: copy content="{{ vault_output['data'].ambassadorkey | b64decode }}" dest="{{ cert_path }}/ambassador.key"
  when: type == "ambassador"

- name: Save rootca file
  local_action: copy content="{{ vault_output['data'].rootca_pem | b64decode }}" dest="{{ cert_path }}/rootca.pem"
  when: type == "rootca"

- name: Save root key
  local_action: copy content="{{ vault_output['data'].rootca_key | b64decode }}" dest="{{ cert_path }}/rootca.key"
  when: type == "rootca"
