##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Gather Kubernetes cluster information
- name: Gather Kubernetes cluster information
  community.kubernetes.k8s_cluster_info:
    kubeconfig: "{{ network['organizations'][0].k8s.config_file }}"
  register: cluster_info

# Set the Kubernetes server URL fact
- name: Set kubernetes_server_url fact
  set_fact:
    kubernetes_server_url: "{{ cluster_info.connection.host }}"

# Install primary genesis
- name: "Install primary genesis"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/create/job_component"
  vars:
    org: "{{ network['organizations'] | first }}"
    name: "{{ org.name | lower }}"
    component_name: "{{ name }}-genesis"
    component_ns: "{{ name }}-quo"
    type: "primary_genesis"
    kubernetes: "{{ org.k8s }}"
    kubernetes_url: "{{ kubernetes_server_url }}"
    vault: "{{ org.vault }}"
    values_dir: "{{ playbook_dir }}/../../../{{ org.gitops.release_dir }}/{{ name }}/build"
    charts_dir: "{{ org.gitops.chart_source }}"

# Check if primary genesis job is completed
- name: "Check if primary genesis job is completed"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    org: "{{ network['organizations'] | first }}"
    name: "{{ org.name | lower }}"
    component_name: "{{ name }}-genesis"
    component_type: Job
    org: "{{ network['organizations'] | first }}"
    component_ns: "{{ org.name | lower }}-quo"
    namespace: "{{ component_ns }}"
    kubernetes: "{{ org.k8s }}"
