##############################################################################################
# This role creates the value file for notary
##############################################################################################

# Wait till the nmap is running
- name: "Waiting for nmap pod to come up"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Pod"
    namespace: "{{ component_ns }}"
    component_name: "{{ org.services.networkmap.name | lower }}"
    kubernetes: "{{ org.k8s }}"
    label_selectors:
      - app = {{ component_name }}

# Create notary ambassador certificates
- name: Create ambassador certficates for notary
  include_role:
    name: create/certificates/cenm
  vars:
    tlscert_path: "./build/ambassador/{{ org.services.notary.name }}"
    service_name: "{{ org.services.notary.name }}"
    dest_path: "./build/ambassador/{{ org.services.notary.name }}/notary.crt"

# Create deployment file for CENM notary service
- name: "Create value file for notary"
  include_role: 
    name: helm_component
  vars:
    component_name: "{{ org.services.notary.name | lower }}"
    type: "notary"
    values_dir: "{{playbook_dir}}/../../../{{ org.gitops.release_dir }}"
    name: "{{ org.name | lower }}"
    notary_legal_name: "{{ org.services.notary.subject }}"
    is_validating: "{{ org.services.notary.validating }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    git_url: "{{ org.gitops.git_ssh }}"
    git_branch: "{{ org.gitops.branch }}"
    node_name: "{{ org.services.notary.name }}"
    storageclass: "cordaentsc"
    init_container_name: "index.docker.io/hyperledgerlabs/alpine-utils:1.0"
    image_pull_secret: "regcred"
    vault_addr: "{{ org.vault.url }}"
    auth_path: "cordaent{{ org.name | lower }}"
    vault_role: "vault-role"
    vault_serviceaccountname: "vault-auth"
    vault_cert_secret_prefix: "secret/{{ org.name | lower }}"
    external_url_suffix: "{{ org.external_url_suffix }}"
    notary_public_ip: "{{ org.services.notary.name }}.{{ org.external_url_suffix }}"
    ssh_username: "{{ org.services.notary.name }}"
    ssh_password: "{{ org.services.notary.name }}P"
    db_username: "{{ org.services.notary.name }}-db-user"
    db_password: "{{ org.services.notary.name }}-db-password"
    db_port: "{{ org.services.notary.dbtcp.port }}"
    idman_url: "{{ network | json_query('orderers[?type==`idman`].uri') | first }}"
    idman_domain: "{{ idman_url.split(':')[1] | regex_replace('/', '') }}"    
    networkmap_url: "{{ network | json_query('orderers[?type==`networkmap`].uri') | first }}"
    networkmap_domain: "{{ networkmap_url.split(':')[1] | regex_replace('/', '') }}"
    corda_service_version: cenm-notary-{{ org.version }}
    p2p_port: "{{ org.services.notary.p2p.port }}"

# Push the notary deployment files to repository
- name: "Push the created deployment files to repository"
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ org.gitops.git_push_url }}"
    GIT_USERNAME: "{{ org.gitops.username }}"
    GIT_EMAIL: "{{ org.gitops.email }}"
    GIT_PASSWORD: "{{ org.gitops.password }}"
    GIT_BRANCH: "{{ org.gitops.branch }}"
    GIT_RESET_PATH: "platforms/corda-ent/configuration"
    msg: "[ci skip] Pushing deployment files for notary service"
