##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role deletes the Vault configurations for each service
#############################################################################################

# Delete Ambassador Creds
- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: "{{ component_name }}"
    name: "{{ service.value['name'] }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  ignore_errors: yes
  changed_when: false

# Delete vault-auth path
- name: Delete vault-auth path
  shell: |
    vault delete sys/auth/corda{{ service.value['name'] }}
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"

# Delete crypto materials from vault
- name: Delete Crypto for services
  shell: |
    vault secrets disable {{ service.value['name'] }}
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  register: test

# Delete vault policies
- name: Delete vault policy
  shell: |
    vault policy delete vault-crypto-{{ component_name }}-{{ service.value['name'] }}-ro
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"

# Delete Ambassador Creds for CA
- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: "{{ component_name }}"
    name: "{{ service.value['name'] }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  changed_when: false
  ignore_errors: yes
