---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodeName }}-conf
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.nodeName }}-conf
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  run.sh: |+
{{ tpl (.Files.Get "files/run.sh") . | indent 4 }}

  set-network-parameters.sh: |+
{{ tpl (.Files.Get "files/set-network-parameters.sh") . | indent 4 }}

  nmap.conf: |+
{{ tpl (.Files.Get "files/nmap.conf") . | indent 4 }}
