##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

charts:
  ca-orderer: fabric-ca-server
  ca-peer: fabric-ca-server
  ca-tools: fabric-catools
  cas: fabric-ca-server
  orderers: fabric-orderernode
  zkkafka: zkkafka
  peers: fabric-peernode
  value_peer: fabric-peernode
  create_channel_job: fabric-channel-create
  osn_create_channel_job: fabric-osnadmin-channel-create
  join_channel_job: fabric-channel-join
  anchorpeer_job: fabric-anchorpeer
  install_chaincode_job: fabric-chaincode-install
  instantiate_chaincode_job: fabric-chaincode-instantiate
  invoke_chaincode_job: fabric-chaincode-invoke
  upgrade_chaincode_job: fabric-chaincode-upgrade
  nms: corda-networkmap
  mongodb: corda-mongodb
  doorman: corda-doorman
  notarydb: corda-h2
  nodedb: corda-h2
  db: corda-ent-h2
  notaryjob: corda-notary-initial-registration
  nodejob: corda-node-initial-registration
  notarynode: corda-notary
  nodenode: corda-node
  tessera: besu-tessera-node
  quorum_tessera: quorum-tessera-node
  quorum: quorum-member-node
  validatorquorum: quorum-validator-node
  memberquorum: quorum-member-node
  pki-generator: cenm-pki-gen
  pki-generator-node: corda-ent-node-pki-gen
  signer: cenm-signer
  gateway: cenm-gateway
  idman: cenm-idman
  zone: cenm-zone
  validator: besu-validator-node
  nmap: cenm-networkmap
  notary-initial-registration: corda-ent-notary-initial-registration
  notary: corda-ent-notary
  bridge: corda-ent-bridge
  float: corda-ent-float
  node_registration: corda-ent-node-initial-registration
  cli: fabric-cli
  commit_chaincode_job: fabric-chaincode-commit
  approve_chaincode_job: fabric-chaincode-approve
  node: corda-ent-node
  crypto_tessera: quorum-tessera-key-mgmt
  besu_crypto_tessera: besu-tessera-key-mgmt
  node_besu: besu-member-node
  cacerts_job: fabric-cacerts-gen
  vault_kubernetes_job: vault_kubernetes
  crypto_ibft_job: quorum-ibft-crypto-gen
  operations_console: fabric-operations-console
  auth: cenm-auth
  substrate_keys_job: substrate-key-mgmt
  vault_k8s_mgmt: bevel-vault-mgmt
  bootnode: substrate-node
  node_substrate: substrate-node
  genesis_job: substrate-genesis
  dscp_ipfs_node: dscp-ipfs-node
  ambassador_besu: besu-tlscert-cert-gen
  certs-ambassador-quorum: quorum-tlscerts-gen
  crypto_raft_job: quorum-raft-crypto-gen
  fabric-connector: fabric-cacti-connector
  besu-connector: besu-cacti-connector
  node_key_mgmt: besu-node-key-mgmt
  quorum-connector: quorum-cacti-connector
  external_chaincode: fabric-external-chaincode
  install_external_chaincode_job: fabric-external-chaincode-install
