##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

charts:
  ca-server: fabric-ca-server
  ca-tools: fabric-catools
  cas: fabric-ca-server
  orderers: fabric-orderernode
  zkkafka: zkkafka
  peers: fabric-peernode
  value_peer: fabric-peernode
  create_channel_job: fabric-channel-create
  osn_create_channel_job: fabric-osnadmin-channel-create
  join_channel_job: fabric-channel-join
  anchorpeer_job: fabric-anchorpeer
  install_chaincode_job: fabric-chaincode-install
  instantiate_chaincode_job: fabric-chaincode-instantiate
  invoke_chaincode_job: fabric-chaincode-invoke
  upgrade_chaincode_job: fabric-chaincode-upgrade
  network_service: corda-network-service
  corda_notary: corda-node
  corda_node: corda-node
  quorum_tessera: quorum-tessera-node
  quorum: quorum-member-node
  validator_quorum: quorum-node
  member_quorum: quorum-node
  pki-generator: cenm-pki-gen
  signer: cenm-signer
  gateway: cenm-gateway
  idman: cenm-idman
  zone: cenm-zone
  nmap: cenm-networkmap
  pki-generator-node: corda-ent-node-pki-gen
  db: corda-ent-h2
  notary-initial-registration: corda-ent-notary-initial-registration
  notary: corda-ent-notary
  bridge: corda-ent-bridge
  float: corda-ent-float
  node_registration: corda-ent-node-initial-registration
  node: corda-ent-node
  cli: fabric-cli
  commit_chaincode_job: fabric-chaincode-commit
  approve_chaincode_job: fabric-chaincode-approve
  crypto_tessera: quorum-tessera-key-mgmt
  besu_member: besu-node
  validator: besu-node
  ambassador_besu: besu-tlscert-gen
  besu-connector: besu-cacti-connector
  cacerts_job: fabric-cacerts-gen
  vault_kubernetes_job: vault_kubernetes
  crypto_ibft_job: quorum-ibft-crypto-gen
  operations_console: fabric-operations-console
  auth: cenm-auth
  substrate_keys_job: substrate-key-mgmt
  vault_k8s_mgmt: bevel-vault-mgmt
  bootnode: substrate-node
  node_substrate: substrate-node
  genesis_job: substrate-genesis
  dscp_ipfs_node: dscp-ipfs-node
  certs-ambassador-quorum: quorum-tlscert-gen
  crypto_raft_job: quorum-raft-crypto-gen
  fabric-connector: fabric-cacti-connector
  quorum-connector: quorum-cacti-connector
  external_chaincode: fabric-external-chaincode
  install_external_chaincode_job: fabric-external-chaincode-install
  generate-keys: indy-key-mgmt
  generate-genesis: indy-genesis
  stewards: indy-node
  corda_ent_notary: enterprise-node
  corda_ent_network_map: cenm-networkmap
  corda_ent_node: enterprise-node

