##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# Create deployment files for all of the steward's nodes sequentially
- name: "Create steward deployment file"
  include_role:
    name: create/helm_component/node
  vars:
    component_type: "node"
    component_name: "{{ organization }}-{{ stewardItem.name }}-node"
    indy_version: "indy-{{ network.version }}"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"

# Push the created deployment files to repository
- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing deployment files for {{ organization }}-{{ stewardItem.name }}-node"

# Wait until steward pods are running
- name: "Wait until steward pods are running"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    namespace: "{{ component_ns }}"
    component_type: "Pod"
    component_name: "{{ organization }}-{{ stewardItem.name }}-node"
    label_selectors:
      - app = {{ component_name }}
