##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################
#                   Basic Configuration                     #
#############################################################
# Default values for substrate-key-mgmt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The following are for overriding global values
global:
  # Provide the service account name which will be created.
  serviceAccountName: global-vault-sa
  cluster:
    provider: # choose from: minikube | aws | azure
    cloudNativeServices: false # 'false' is implemented
    #Provide the kubernetes host url
    #Eg. kubernetesUrl: https://10.3.8.5:6443
    kubernetesUrl:
  vault:
    # Provide the type of vault
    type: hashicorp # hashicorp | kubernetes
    # Provide the vault role used.
    role: # global-vault-role
    # Provide the network type
    network: substrate
    # Provide the vault server address
    address: # "http://vault_url"
    # Provide the vault authPath configured to be used.
    authPath: oem
    # Provide the secret engine.
    secretEngine: secretsv2
    # Provide the vault path where the secrets will be stored
    secretPrefix: "data/oem"

removeGenesisOnDelete:
  enabled: true
  image:
    repository: ghcr.io/hyperledger/bevel-k8s-hooks
    tag: qgt-0.2.12
    pullPolicy: IfNotPresent

# Provide custom chain name
# Eg. chain: inteli-gcp
chain: inteli

node:
  # Pull substrate Docker image
  image: ghcr.io/inteli-poc/dscp-node
  # Substrate image tag
  imageTag: v4.3.1
  # Pull policy to be used for the Docker image
  # Eg. pullPolicy: IfNotPresent
  pullPolicy: IfNotPresent
  # Command to be invoked to perform operations on the node
  # Eg. command: substrate
  command: ./dscp-node
  member:
    balance: 1152921504606846976

org_namespaces:
  - oem-subs:
      validator:
        - oem-validator-1
        - oem-validator-2
      member:
        - oem-member-1
  - tierone-subs:
      validator:
        - tierone-validator-3
        - tierone-validator-4
      member:
        - tierone-member-2
  - tiertwo-subs:
      validator:
      member:
        - tiertwo-member-3
