---
#helm install member-2 -f values/proxy-and-vault/txnode-sec.yml -n carrier-bes --set global.proxy.p2p=15016 besu-node
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
    kubernetes_url: https://34D2F36E71F0880BE63D943D2E503A9B.gr7.eu-west-1.eks.amazonaws.com
  vault:
    type: hashicorp
    network: besu
    address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
    authPath: besunode2
    secretEngine: secretsv2
    secretPrefix: "data/carrier"
    role: vault-role
  proxy:
    provider: ambassador
    externalUrlSuffix: bes.demo.aws.blockchaincloudpoc.com

storage:
  size: "2Gi"

tessera:
  enabled: true
  tessera:
    port: 443
    peerNodes: 
      - url: "https://member-1.bes.demo.aws.blockchaincloudpoc.com"
  resources:
    cpuLimit: 1
    cpuRequest: 0.5
    memLimit: "2G"
    memRequest: "1G"
    password: 'password'
  storage:
    enabled: false
    size: 1Gi
    dbSize: 2Gi
    allowedTopologies:
      enabled: false
  
  tls:
    enabled: true
    settings:
      certSubject: CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB
      tmTls: true

node:
  removeKeysOnDelete: false # this will erase keys - so be careful with this on validators
  isBootnode: false    # set this to true if this node is a bootnode
  usesBootnodes: false
  besu:
    envBesuOpts: ""  
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    account:
      password: 'password'
image:
  besu:
    repository: hyperledger/besu
    tag: 22.10.2