##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "1.0"
name: cenm-zone
description: "R3-corda-ent: Deploys the CENM zone."
version: '0.15.0'
