---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "besu-tessera-node.fullname" . }}-pre-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "hook-succeeded"
  labels:
    app.kubernetes.io/name: pre-delete-hook
    app.kubernetes.io/component: job
    app.kubernetes.io/part-of: {{ include "besu-tessera-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  backoffLimit: 3
  completions: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pre-delete-hook
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.global.serviceAccountName }}
      restartPolicy: "OnFailure"
      containers:
        - name: {{ template "besu-tessera-node.fullname" . }}-node-pre-delete-hook
          image: "{{ .Values.image.hooks.repository }}:{{ .Values.image.hooks.tag }}"
          imagePullPolicy: {{ .Values.image.hooks.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - |

              echo "{{ template "besu-tessera-node.fullname" . }} Pre Delete hook ..."

{{- if and (eq .Values.global.vault.type "hashicorp") (not .Values.global.cluster.cloudNativeServices) }}
              . /scripts/bevel-vault.sh
              echo "Getting vault Token..."
              vaultBevelFunc "init"
              function deleteSecret {
                key=$1
                #delete secret from vault
                vaultBevelFunc 'delete' "${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/${key}"
              }

{{- else }}

              function deleteSecret {
                key=$1
                kubectl delete secret ${key} --namespace {{ .Release.Namespace }}
              }

{{- end }}

              function delete_node_from_tessera_peers_configmap {
                kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o json
                # if there is no configmap, do nothing
                if [ $? -ne 0 ]; then
                  echo "No tessera-peers found, nothing to do..."
                # delete the one
                else
                  echo "tessera-peers found, deleting {{ template "besu-tessera-node.fullname" . }}..."
                  echo $(kubectl -n {{ .Release.Namespace }} get configmap tessera-peers -o jsonpath='{.data.tesseraPeers}' ) > /tmp/tessera-peers.raw
                  cat /tmp/tessera-peers.raw | jq --arg NEEDLE "{{ template "besu-tessera-node.fullname" . }}" 'del(.[] | select( .url | contains($NEEDLE) ))' > /tmp/tessera-peers
                  kubectl -n {{ .Release.Namespace }} create configmap tessera-peers --from-file=tesseraPeers=/tmp/tessera-peers -o yaml --dry-run=client | kubectl replace -f -
                fi
              }

              delete_node_from_tessera_peers_configmap

{{- if .Values.quorumFlags.removeKeysOnDelete }}

{{- if and (ne .Values.global.cluster.provider "local") (.Values.global.cluster.cloudNativeServices) }}
              deleteSecret {{ template "besu-tessera-node.fullname" . }}-tmkey
              deleteSecret {{ template "besu-tessera-node.fullname" . }}-tmkeypub
              deleteSecret {{ template "besu-tessera-node.fullname" . }}-tmpassword
{{- else }}
              deleteSecret {{ template "besu-tessera-node.fullname" . }}-tessera-keys
{{- end }}

{{- end }}
              echo "Completed"
