##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu-tessera-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "besu-tessera-node.fullname" . }}
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: {{ include "besu-tessera-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/release: {{ .Release.Name }}
    {{- if $.Values.labels }}
    {{- range $key, $value := $.Values.labels.service }}
    {{- range $k, $v := $value }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ include "besu-tessera-node.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
  - name: tm-manager
    protocol: TCP
    port: {{ .Values.tessera.port }}
    targetPort: {{ .Values.tessera.port }}
  - name: clientport
    protocol: TCP
    port: {{ .Values.tessera.q2tport }}
    targetPort: {{ .Values.tessera.q2tport }}
  - name: tm-tessera-third-part
    protocol: TCP
    port: 9080
    targetPort: 9080
  - name: mysql-db
    protocol: TCP
    port: {{ .Values.tessera.dbport }}
    targetPort: {{ .Values.tessera.dbport }}
{{- if eq $.Values.global.proxy.provider "ambassador" }}
## Host for tm connection
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: {{ .Release.Name }}-host
spec:
  hostname: {{ .Release.Name }}.{{ .Values.global.proxy.externalUrlSuffix }}
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Reject
  tlsSecret:
    name: tls-tls-certs
    namespace: {{ .Release.Namespace }}
## Mapping for tm port
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ .Release.Name }}-mapping
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}.{{ .Values.global.proxy.externalUrlSuffix }}
  prefix: /
  service: {{ include "besu-tessera-node.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.tessera.port }}
  tls: {{ .Release.Name }}-tlscontext
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: {{ .Release.Name }}-tlscontext
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Release.Name }}.{{ .Values.global.proxy.externalUrlSuffix }}
  secret: tls-tls-certs.{{ .Release.Namespace }}
  secret_namespacing: true
  min_tls_version: v1.2
{{- end }}
