##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
# Besu binary version
appVersion: '21.10.6'
description: "Hyperledger Besu: Deploys Hyperledger Besu nodes"
name: besu-member-node
version: '0.15.0'
