##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
global:
  serviceAccountName: vault-auth
  vault:
    type: "hashicorp"
    network: substrate
    address: "http://vault.demo.com:8200"
    authPath: tierone
    secretEngine: secretsv2
    secretPrefix: "data/tierone"
    role: vault-role
proxy:
  provider: ambassador 
