##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Quorum: This Helm chart deploys a validator Quorum node."
name: quorum-validator-node
version: '0.15.0'
