##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v1
name: quorum-node
description: "Quorum: Deploys a Quorum node for a POA network"
version: 1.1.0
appVersion: latest
keywords:
  - bevel
  - ethereum
  - quorum
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
