##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Remove old genesis block
- name: Remove old genesis block
  file:
    path: "{{ build_path }}/channel-artifacts/genesis.block"
    state: absent

# Create the genesis block by consuming the configtx.yaml file
- name: "Create genesis block"
  shell: |
    cd {{ build_path }}
    {% if '2.5' in network.version %}
    ./configtxgen -profile {{ genesis.name }} -channelID {{ channel_name }} -outputBlock ./channel-artifacts/genesis.block
    {% elif '2.2' in network.version %}
    ./configtxgen -profile {{ genesis.name }} -channelID syschannel  -outputBlock ./channel-artifacts/genesis.block
    {% else %}
    ./configtxgen -profile {{ genesis.name }} -channelID syschannel -outputBlock ./channel-artifacts/genesis.block
    {% endif %}
    cat ./channel-artifacts/genesis.block | base64 > ./channel-artifacts/genesis.block.base64
  when: add_new_org == 'false'

# Write genesis block to Vault
- name: "Write genesis block to Vault"  
  shell: |
    vault kv put {{ org.vault.secret_path | default('secretsv2') }}/crypto/ordererOrganizations/{{ org.name }}-net {{ network.env.type }}GenesisBlock=@{{build_path}}/channel-artifacts/genesis.block.base64
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  loop: "{{ network['organizations'] }}"
  loop_control:
    loop_var: org
  when: add_new_org == 'false' and org.type == "orderer"
