# Create Value files for Genesis 
- name: Create Value files for Genesis 
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/create/job_component"
  vars:
    name: "{{ org.name | lower }}"
    component_ns: "{{ org.name | lower }}-net"
    component_name: "genesis"
    consensus: "{{ network.consensus }}"
    type: "fabric_genesis"
    kubernetes: "{{ org.k8s }}"
    vault: "{{ org.vault }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    values_dir: "{{playbook_dir}}/../../../{{org.gitops.component_dir}}/{{ org.name | lower }}"
    generateGenisisBLock: "{{ generateGenisis }}"
    add_org: "{{ add_new_org | default(false) }}"

# Git Push: Push the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ org.gitops }}"
    msg: "[ci skip] Pushing Genesis files"
