##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
name: besu-cacti-connector
description: "Hyperledger Besu: Deploys Cactus Besu Connector"
type: application
version: 1.1.0
# For Cactus release 1.1.3
appVersion: "1.1.3"
