##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

metadata:
  # HLF network version
  network:
    version: 2.2.2
  #Provide the namespace for organization's peer
  #Eg. namespace: org1-net
  namespace: org1-net
  images:
    #Provide the valid image name and version for fabric tools
    #Eg. fabrictools: hyperledger/fabric-tools:1.4.0
    fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.2.2
    #Provide the valid image name and version to read certificates from vault server
    #Eg.alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the custom labels
  #NOTE: Provide labels other than name, release name , release service, chart version , chart name , app.
  #Eg. labels:
  #      role: create_channel
  labels:


peer:
  #Provide the name of the peer as per deployment yaml.
  #Eg. name: peer0
  name: peer0
  #Provide the address of the peer who creates the channel and port to be mentioned is grpc cluster IP port
  #Eg. address: peer0.org1-net:7051
  address: peer0.org1-net:7051
  #Provide the localmspid for organization
  #Eg. localmspid: Org1MSP
  localmspid: Org1MSP
  #Provide the loglevel for organization's peer
  #Eg. loglevel: info
  loglevel: info
  #Provide the value for tlsstatus to be true or false for organization's peer
  #Eg. tlsstatus: true
  tlsstatus: true


vault:
  #Provide the vaultrole for an organization
  #Eg. vaultrole: vault-role
  role: vault-role
  #Provide the vault server address
  #Eg. vaultaddress: http://Vault-884963190.eu-west-1.elb.amazonaws.com
  address:
  #Provide the kubernetes auth backed configured in vault for an organization
  #Eg. authpath: devorg1-net-auth
  authpath: devorg1-net-auth
  # Vault secretprefix for chaincode
  chaincodesecretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/peers/peer0.org1-net/chaincodes
  #Provide the value for vault secretprefix
  #Eg. adminsecretprefix: secretsv2/data/crypto/peerOrganizations/.../users/admin
  adminsecretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/users/admin
  #Provide the value for vault secretprefix
  #Eg. orderersecretprefix: secretsv2/data/crypto/peerOrganizations/.../orderer
  orderersecretprefix: secretsv2/data/crypto/peerOrganizations/org1-net/orderer
  #Provide the serviceaccountname for vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname: vault-auth
  #Provide the type of vault
  #Eg. type: hashicorp
  type: hashicorp
  #Provide the imagesecretname for vault
  #Eg. imagesecretname: regcred
  imagesecretname: ""
  #Provide the secretgitprivatekey
  #Eg. secretgitprivatekey: secret/credentials/org1-net/git?ssh-key
  secretgitprivatekey: secretsv2/data/credentials/org1-net/git?git_password
  #Kuberenetes secret for vault ca.cert
  #Enable or disable TLS for vault communication if value present or not
  #Eg. tls: vaultca
  tls: 
  #Provide the path of the package details saved in base64 format
  #Eg. secretgitprivatekey: secretsv2/data/crypto/peerOrganizations/org1-net/.../example/package/v1
  chaincodepackageprefix: secretsv2/data/crypto/peerOrganizations/org1-net/chaincodes/example/package/v1

chaincode:
  #Provide the name of the chaincode to be installed
  #Eg. name: cc
  name: example
  #Provide the chaincode version to be installed
  #Eg. version: "1"
  version: 1
  # if tls is disabled or not | BOOLEAN | eg. true
  tls_disabled: true
  # Chaincode server address eg. chaincode-marbles-1-carrier.carrier-net.svc.cluster.local:7052
  address:
