##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Shared: Deploys a StorageClass that can be used to provision persistent volumes for nodes."
name: bevel-storageclass
version: '0.15.0'
