##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.nodeName }}
# we need healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}  
  ports:
  - name: bridge-tunnel
    protocol: TCP
    port: {{ .Values.bridge.tunnelPort }}
    targetPort: {{ .Values.bridge.tunnelPort }}
  - name: p2p
    protocol: TCP
    port: {{ .Values.node.p2pPort }}
    targetPort: {{ .Values.node.p2pPort }}
{{- if $.Values.ambassador }}
---
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: {{ .Values.nodeName }}-{{ .Values.peerName }}-p2p
  namespace: {{ .Values.metadata.namespace }}
spec:
  port:  {{ .Values.ambassador.p2pPort }}
  service: {{ .Values.nodeName }}.{{ .Values.metadata.namespace }}:{{ .Values.node.p2pPort }}
---
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: {{ .Values.nodeName }}-{{ .Values.peerName }}-tunnel
  namespace: {{ .Values.metadata.namespace }}
spec:
  port:  {{ .Values.ambassador.tunnelPort }}
  service: {{ .Values.nodeName }}.{{ .Values.metadata.namespace }}:{{ .Values.node.p2pPort }}
{{- end }}
