##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.nodeName }}
  # we need healthCheckNodePort set to get rid of logs pollution
  {{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
  {{- end }}
  {{- if (.Values.service.type) }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.messagingServerPort }}
      targetPort: {{ .Values.service.messagingServerPort }}
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.rpc.port }} 
      targetPort: {{ .Values.service.rpc.port }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.ssh.sshdPort }} 
      targetPort: {{ .Values.service.ssh.sshdPort }}
      protocol: TCP
      name: ssh
{{- if and ($.Values.nodeConf.ambassador.p2pAddress) (eq .Values.firewall.enabled false)  }}
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: {{ .Values.nodeName }}-host
spec:
  hostname: {{ .Values.nodeName }}.{{ .Values.nodeConf.ambassador.external_url_suffix }}
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Reject
  tlsSecret:
    name: {{ .Values.nodeName }}-ambassador-certs
    namespace: {{ .Values.metadata.namespace }}
  tls:
    min_tls_version: v1.2
---
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: {{ .Values.nodeName }}-p2p
  namespace: {{ .Values.metadata.namespace }}
spec:
  host: {{ .Values.nodeName }}.{{ .Values.nodeConf.ambassador.external_url_suffix }}
  port:  {{ .Values.nodeConf.ambassador.p2pPort }}
  service: {{ .Values.nodeName }}.{{ .Values.metadata.namespace }}:{{ .Values.service.p2pPort }}
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: {{ .Values.nodeName }}-tlscontext
  namespace: {{ .Values.metadata.namespace }}
spec:
  hosts:
  - {{ .Values.nodeName }}.{{ .Values.nodeConf.ambassador.external_url_suffix }}
  secret: {{ .Values.nodeName }}-ambassador-certs.{{ .Values.metadata.namespace }}
  secret_namespacing: true
  min_tls_version: v1.2
{{- end }}
