##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "R3-corda-os: Deploys networkmap service without TLS."
name: corda-networkmap
version: '0.15.0'
