helm_templates:
  pki-generator: pki-generator.tpl
  signer: create_signer.tpl
  idman: idman.tpl
  nmap: nmap.tpl
  notary-initial-registration: notary_initial_registration.tpl
  db: db.tpl
  notary: notary.tpl
  bridge: bridge.tpl
  float: float.tpl
  node_registration: node_registration.tpl
  node: node.tpl
corda_enterprise_image:
  cenm-networkmap-1.2: corda/enterprise-networkmap:1.2-zulu-openjdk8u242
  cenm-notary-1.2: adopblockchaincloud0502.azurecr.io/corda_image_notary_1.2:latest
  firewall: adopblockchaincloud0502.azurecr.io/corda_image_firewall_4.4:latest
  node: adopblockchaincloud0502.azurecr.io/corda_image_ent_4.4:latest
