#############################################################################################
#                      This role deletes the channel artifacts                              #       
#############################################################################################

# This task deletes the BASE 64 encoded genesis blocks for all channels
- name: Delete genesis block from Vault
  shell: |
    vault delete secret/crypto/ordererOrganizations
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  ignore_errors: yes
  loop: "{{ network['organizations'] }}"
  loop_control:
    loop_var: org
  when: org.type == "orderer"
