---
# helm install member-1 -f values/noproxy-and-novault/txnode.yml -n supplychain-quo quorum-node 
# helm upgrade member-1 -f values/noproxy-and-novault/txnode.yml -n supplychain-quo quorum-node
global:
  serviceAccountName: vault-auth
  cluster:
    cloudNativeServices: false # true | false
    provider: aws
    secretManagerRegion: 
  vault:
    type: kubernetes # kubernetes
  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local

tessera:
  enabled: true
  tessera:
    tlsMode: "OFF"
  resources:
    cpuLimit: 0.25
    cpuRequest: 0.05
    memLimit: "2G"
    memRequest: "1G"
    password: 'password'
  storage:
    enabled: false
    size: 1Gi
    dbSize: 2Gi
    allowedTopologies:
      enabled: false

tls:
  enabled: false
  settings:
    certSubject: CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB
    tmTls: true

node:
  goquorum:
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 0.25
      cpuRequest: 0.05
      memLimit: "1G"
      memRequest: "300M"
    account:
      password: 'password'
