---
# helm install member-2 -f values/noproxy-and-novault/txnode-sec.yml -n carrier-quo quorum-node
global:
  serviceAccountName: vault-auth
  cluster:
    cloudNativeServices: false # true | false
    provider: aws
    secretManagerRegion: 
  vault:
    type: kubernetes # kubernetes
  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local

tessera:
  enabled: true
  tessera:
    tlsMode: "OFF"
    peerNodes: 
      - url: "http://quorum-tessera-node-member-0.supplychain-quo:9000"
  resources:
    cpuLimit: 0.25
    cpuRequest: 0.05
    memLimit: "2G"
    memRequest: "1G"
    password: 'password'
  storage:
    enabled: false
    size: 1Gi
    dbSize: 2Gi
    allowedTopologies:
      enabled: false

tls:
  enabled: false

node:
  goquorum:
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 0.25
      cpuRequest: 0.05
      memLimit: "1G"
      memRequest: "300M"
    account:
      password: 'password'
