---
# helm install validator-1 -f values/noproxy-and-novault/validator.yml -n supplychain-quo quorum-node
# helm upgrade validator-1 -f values/noproxy-and-novault/validator.yml -n supplychain-quo quorum-node
global:
  serviceAccountName: vault-auth
  cluster:
    cloudNativeServices: false # true | false
    provider: aws
    secretManagerRegion: 
  vault:
    type: kubernetes # kubernetes

  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local
