apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  {{ if $.Values.nodeConf.ambassador.p2pAddress }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: {{ .Values.nodeName }}_context
      hosts:
      - {{ .Values.nodeName }}.{{ .Values.nodeConf.ambassador.external_url_suffix }}
      secret: {{ .Values.nodeName }}-ambassador-certs
      ---
      apiVersion: ambassador/v1
      kind: TCPMapping
      name: {{ .Values.nodeName }}_p2p_mapping
      port: {{ .Values.nodeConf.ambassador.p2pPort }}
      host: {{ .Values.nodeName }}.{{ .Values.nodeConf.ambassador.external_url_suffix }}
      service: {{ .Values.nodeName }}.{{ .Values.metadata.namespace }}:{{ .Values.service.p2pPort }}
  {{ end }}  
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.nodeName }}
  # we need healthCheckNodePort set to get rid of logs pollution
  {{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
  {{- end }}
  {{- if (.Values.service.type) }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.rpc.port }} 
      targetPort: {{ .Values.service.rpc.port }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.ssh.sshdPort }} 
      targetPort: {{ .Values.service.ssh.sshdPort }}
      protocol: TCP
      name: ssh
