##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Create the helm release files for each new validator node of organization
- name: Create the helm release files for each new validator node
  include_role:
    name: create/helm_component
  vars:
    component_name: "{{ name }}{{ peer.name }}validator_node"
    type: "validator"
    genesis: "{{ lookup('file', '{{ network.config.genesis }}') }}"
    nodelist: "{{lookup('file', '{{ build_path }}/{{ peer_val.name }}/{{ peer.name }}/nodelist').split('\n')| join(',') }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer_val  
  when: peer.status == 'new'

# Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ org_val.gitops }}"
    msg: "[ci skip] Pushing Peer files"
