---
- name: Delete Helm release
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl delete secret git-auth-{{ network.env.type }} -n default
    KUBECONFIG={{ kubernetes.config_file }} helm uninstall flux-{{ network.env.type }}
    KUBECONFIG={{ kubernetes.config_file }} helm uninstall flux-{{ network.env.type }}-helm-operator
    KUBECONFIG={{ kubernetes.config_file }} helm uninstall alice
  ignore_errors: yes

- name: Wait for deleting of Helm release flux-{{ network.env.type }}
  k8s_info:
    kind: "Pod"
    label_selectors:
    - release=flux-{{ network.env.type }}
    namespace: "default"
    kubeconfig: "{{ kubernetes.config_file }}"
  register: result
  until: result.resources|length == 0
  retries: "{{ network.env.retry_count }}"
  delay: 40
