helm_templates:
  pki-generator: pki-generator.tpl
  signer: signer.tpl
  idman: idman.tpl
  nmap: nmap.tpl
  notary-initial-registration: notary_initial_registration.tpl
  db: db.tpl
  notary: notary.tpl
  bridge: bridge.tpl
  float: float.tpl
  node_registration: node_registration.tpl
  node: node.tpl
docker_images:
  cenm:
    pki-1.2: corda/enterprise-pki:1.2-zulu-openjdk8u242
    networkmap-1.2: corda/enterprise-networkmap:1.2-zulu-openjdk8u242
    idman-1.2: corda/enterprise-identitymanager:1.2-zulu-openjdk8u242
    notary-1.2: corda/enterprise-notary:1.2-zulu-openjdk8u242
    firewall: corda_image_firewall_4.4:latest
    node: corda_image_ent_4.4:latest
  init_container: alpine-utils:1.0
