##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

helm_templates:
  corda_ent_notary: corda_ent_notary.tpl
  corda_ent_network_map: corda_ent_network_map.tpl
  corda_ent_node: node.tpl
docker_images:
  cenm:
    # list of various nodes supporting version 1.2
    pki-1.2: corda/enterprise-pki:1.2-zulu-openjdk8u242
    signer-1.2: corda/enterprise-signer:1.2-zulu-openjdk8u242
    idman-1.2: corda/enterprise-identitymanager:1.2-zulu-openjdk8u242
    networkmap-1.2: corda/enterprise-networkmap:1.2-zulu-openjdk8u242
    # list of various nodes supporting version 1.5
    pki-1.5: corda/enterprise-pki:1.5.1-zulu-openjdk8u242
    signer-1.5: corda/enterprise-signer:1.5.1-zulu-openjdk8u242
    idman-1.5: corda/enterprise-identitymanager:1.5.1-zulu-openjdk8u242
    networkmap-1.5: corda/enterprise-networkmap:1.5.1-zulu-openjdk8u242
    auth-1.5: corda/enterprise-auth:1.5.1-zulu-openjdk8u242
    zone-1.5: corda/enterprise-zone:1.5.1-zulu-openjdk8u242
    gateway-1.5: corda/enterprise-gateway:1.5.0-zulu-openjdk8u242
    enterpriseCli-1.5: corda/enterprise-cli:1.5.1-zulu-openjdk8u242
    # list of various nodes supporting version 4.4
    firewall-4.4: corda/enterprise-firewall:4.4
    node-4.4: corda/enterprise-node:4.4
    notary-4.4: corda/enterprise-node:4.4
    # list of various nodes supporting version 4.7
    node-4.7: corda/enterprise-node:4.7
    notary-4.7: corda/enterprise-node:4.7
    # list of various nodes supporting version 4.10
    node-4.10: corda/enterprise-node:4.10
    notary-4.10: corda/enterprise-node:4.10
  init_container: alpine-utils:1.0
