##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Hyperledger Fabric: Upgrades chaincode on a peer."
name: fabric-chaincode-upgrade
version: '0.15.0'
