##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Provide the number of replicas for pods
#Eg. replicaCount: 1
replicaCount: 1

metadata:
  #Provide the namespace for the Quorum node
  #Eg. namespace: example-quo
  namespace: default
  #Provide the custom labels  
  #NOTE: Provide labels other than name, release name , release service, chart version , chart name, run
  #These lables will not be applied to VolumeClaimTemplate of StatefulSet as labels are automatically picked up by Kubernetes
  #Eg. labels:
  #      role: minter
  labels:

#These are the various docker images being used by this chart. update them as needed
images:
  #Provide the valid image name and version to read certificates from vault server 
  #Eg. alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
  alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the valid image name and version for quorum tessera
  #Eg. tessera: quorumengineering/tessera:0.9.2
  tessera: quorumengineering/tessera:0.9.2
  #Provide the valid image name and version for busybox
  busybox: busybox
  #Provide the valid image name and version for MySQL. This is used as the DB for TM
  mysql: mysql/mysql-server:5.7

node:
  #Provide the name for Tessera node
  #Eg. name: node-1
  name: node-1
  #Provide the mountpath for Quorum pod
  #Eg. mountPath: /etc/quorum/qdata
  mountPath: /etc/quorum/qdata
  #Provide the docker secret name in the namespace
  #Eg. imagePullSecret: regcred
  imagePullSecret: regcred
  #Provide the k8s service type
  servicetype: ClusterIP
  #Provide the container and service ports
  ports:
    tm: 15013
    db: 3306
  #Provide the mysql DB name
  #Eg. dbname: demodb
  dbname: demodb
  #Provide the mysql username
  #Eg. mysqluser: demouser
  mysqluser: demouser 

vault:
  type: hashicorp
  #Provide the Vault Address from where secrets will be read
  #Eg. address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9000
  address: 
  #Provide the Vault secret path from where secrets will be read
  #Eg. secretprefix: secret/org1/crypto/node_1
  secretprefix: secret/org1/crypto/node_1
  #Provide the serviceaccount which is verified with Vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname: vault-auth
  #Provide the key name from where quorum secrets will be read
  #Eg. keyname: quorum
  keyname: quorum
  #Provide the service role which is verified with Vault
  #Eg. role: vault-role
  role: vault-role
  #Provide the Vault auth-path which is created for the namespace
  #Eg. authpath: quorumorg1
  authpath: quorumorg1

tessera:
  #Provide the Database URL
  #Eg. dburl: jdbc:mysql://localhost:3306/demodb
  dburl: jdbc:mysql://localhost:3306/demodb
  #Provide the Database username
  #Eg. dbusername: $username
  dbusername: demouser
  #Provide the tessera node's own url. This should be local. Use http if tls is OFF
  #Eg. url: "https://node1.quo.demo.aws.blockchaincloudpoc.com"
  url: 
  clienturl: 
  #Provide the list of tessera nodes to connect in url: <value> format. This should be reachable from this node
  #Eg. othernodes: 
  #     - url: "https://node1.quo.demo.aws.blockchaincloudpoc.com"
  #     - url: "https://node2.quo.demo.aws.blockchaincloudpoc.com"
  othernodes: 
  #Provide if tessera will use tls. 
  # Options:
  ##   - STRICT: All connections to and from this node must use TLS with mutual
  ##     authentication. 
  ##   - OFF: Mutually authenticated TLS is not used for in- and outbound
  ##     connections, although unauthenticated connections to HTTPS hosts are
  ##     still possible. This should only be used if another transport security
  ##     mechanism like WireGuard is in place.
  #Eg. tls: 'STRICT'
  tls: STRICT
  #Provide the server/client  trust configuration for transaction manager nodes. 
  # options are: "WHITELIST", "CA_OR_TOFU", "CA", "TOFU"
  # Eg: trust: "TOFU"
  trust: TOFU

proxy:
  #This will be the proxy/ingress provider. Can have values "ambassador" or "haproxy"
  # TODO "haproxy" has not been tested
  #Eg. provider: "ambassador"
  provider: "ambassador"
  #This field contains the external URL of the node
  #Eg. external_url: node1.quo.demo.aws.blockchaincloudpoc.com
  external_url: 
  # Following are the ports that are exposed externally via the proxy
  clientport: 15032

storage:
  #Provide the kubernetes storageclass for node
  #Eg. storageclassname: awsstorageclass
  storageclassname: awsstorageclass
  #Provide the memory for node
  #Eg. storagesize: 1Gi
  storagesize: 1Gi
  #Provide the memory for database
  #Eg. dbstorage: 1Gi
  dbstorage: 1Gi
