# Default values for ambassador.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Manually set metadata for the Release.
#
# Defaults to .Chart.Name
nameOverride: edge-stack
# Defaults to .Release.Name-.Chart.Name unless .Release.Name contains "ambassador"
fullnameOverride: ''
# Defaults to .Release.Namespace
namespaceOverride: ''

# Emissary Chart Values.
emissary-ingress:
  service:
    type: LoadBalancer

    # Note that target http ports need to match your ambassador configurations service_port
    # https://www.getambassador.io/reference/modules/#the-ambassador-module
    ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: tcp-15010
      port: 15010
      targetPort: 15010
    - name: tcp-15011
      port: 15011
      targetPort: 15011
    - name: tcp-15012
      port: 15012
      targetPort: 15012
    - name: tcp-15013
      port: 15013
      targetPort: 15013
    - name: tcp-15014
      port: 15014
      targetPort: 15014
    - name: tcp-15015
      port: 15015
      targetPort: 15015
    - name: tcp-15016
      port: 15016
      targetPort: 15016
    - name: tcp-15017
      port: 15017
      targetPort: 15017
    - name: tcp-15018
      port: 15018
      targetPort: 15018
    - name: tcp-15019
      port: 15019
      targetPort: 15019
    - name: tcp-15020
      port: 15020
      targetPort: 15020
    - name: tcp-15021
      port: 15021
      targetPort: 15021
    - name: tcp-15022
      port: 15022
      targetPort: 15022
    - name: tcp-15023
      port: 15023
      targetPort: 15023
    - name: tcp-15024
      port: 15024
      targetPort: 15024
    - name: tcp-15025
      port: 15025
      targetPort: 15025
    - name: tcp-15026
      port: 15026
      targetPort: 15026
    - name: tcp-15027
      port: 15027
      targetPort: 15027
    - name: tcp-15028
      port: 15028
      targetPort: 15028
    - name: tcp-15029
      port: 15029
      targetPort: 15029
    - name: tcp-15030
      port: 15030
      targetPort: 15030
    - name: tcp-15031
      port: 15031
      targetPort: 15031
    - name: tcp-15032
      port: 15032
      targetPort: 15032
    - name: tcp-15033
      port: 15033
      targetPort: 15033
    - name: tcp-15034
      port: 15034
      targetPort: 15034
    - name: tcp-15035
      port: 15035
      targetPort: 15035
    - name: tcp-15036
      port: 15036
      targetPort: 15036
    - name: tcp-15037
      port: 15037
      targetPort: 15037
    - name: tcp-15038
      port: 15038
      targetPort: 15038
    - name: tcp-15039
      port: 15039
      targetPort: 15039
    - name: tcp-15040
      port: 15040
      targetPort: 15040
    - name: tcp-15041
      port: 15041
      targetPort: 15041
    - name: tcp-15042
      port: 15042
      targetPort: 15042
    - name: tcp-15043
      port: 15043
      targetPort: 15043
    - name: tcp-15044
      port: 15044
      targetPort: 15044
    - name: tcp-15045
      port: 15045
      targetPort: 15045
    - name: tcp-15046
      port: 15046
      targetPort: 15046
    - name: tcp-15047
      port: 15047
      targetPort: 15047
    - name: tcp-15048
      port: 15048
      targetPort: 15048
    - name: tcp-15049
      port: 15049
      targetPort: 15049
    - name: tcp-15050
      port: 15050
      targetPort: 15050
  adminService:
    # Passed to cloud provider load balancer if created (e.g: AWS ELB)
    loadBalancerSourceRanges: 

  # Whether Emissary should be created with default listeners:
  # - HTTP on port 8080
  # - HTTPS on port 8443
  createDefaultListeners: true

################################################################################
## Ambassador Edge Stack Configuration                                        ##
################################################################################
redis:
  image:
    tag: 7.2.4
# The Ambassador Edge Stack is free for limited use without a license key.
# Go to https://{ambassador-host}/edge_stack/admin/#dashboard to register
# for a community license key.

licenseKey:
  value:
  createSecret: true
  secretName:
  # Annotations to attach to the license-key-secret.
  annotations: {}

