##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for nmschart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Provide the Name for node to be deployed
#Eg. nodeName: network-map
nodeName: network-map

metadata:
  #Provide the namespace
  #Eg. namespace: default
  namespace: default

image:
  #Provide the name of image for init container
  #Eg. initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
  initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the containerName of image
  containerName: ghcr.io/hyperledger/bevel-networkmap-linuxkit:latest
  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  imagePullSecret: 
  #Provide enviroment variable for container image
  env:
    #Provide rootcaname for the doorman
    #Eg. rootcaname: CN=Corda Root CA, OU=FRA, O=FRA, L=London, ST=London, C=BR
    rootcaname:
    tlscertpath:
    tlskeypath:
    #Provide whether TLS is enabled or not
    #Eg. tls: false
    tls:
    #Provide whether to enable Corda doorman protocol
    #Eg. doorman: true
    doorman:
    #Provide whether to enable Cordite certman protocol so that nodes can authenticate using a signed TLS cert
    #Eg. certman: true
    certman:
    #Provide database directory for this service
    #Eg. database: db
    database:
    #Provide MongoDB connection string. If set to embed will start its own mongo instance
    #Eg. dataSourceUrl: db
    dataSourceUrl:
  
service:
  #Provide the NMS service port 
  #Eg. port: 30007
  port: 30007
  #Provide the type of service
  #Eg. type: NodePort
  type: NodePort
  #Provide the node port for node service to be accessible outside
  #Eg. nodePort: 30050
  nodePort: 

storage:
  #Provide the memory for node
  #Eg. memory: 4Gi
  memory: 4Gi

vault:
  #Provide the vault server address
  #Eg. address: http://34.228.219.208:8200
  address:
  #Provide the vaultrole
  #Eg. role: vault-role
  role: vault-role
  #Eg. authpath: cordanms
  authpath: cordanms
  #Provide the kubernetes auth backed configured in vault
  #Eg. secretprefix:
  secretprefix:
  #Eg. imagesecretname:
  imagesecretname:
  #Eg. serviceaccountname: vault-auth-issuer
  serviceaccountname: vault-auth-issuer
  #Path in vault where tls certificates are present
  tlscertsecretprefix:

ambassador:
  #Provides the suffix to be used in external URL
  #Eg. external_url_suffix: org1.blockchaincloudpoc.com
  external_url_suffix:
