##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v1
name: besu-tessera-node
description: "Hyperledger Besu: Deploys Tessera transaction manager nodes"
version: 1.1.0
# Tessera version 
appVersion: '21.7.3'
keywords:
  - bevel
  - tessera
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
