#helm install genesis -f values/noproxy-and-novault/genesis.yaml -n supplychain-bes besu-genesis
global:
  serviceAccountName: bevel-auth
  vault:
    type: kubernetes
  cluster:
    provider: aws
    cloudNativeServices: false
    
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    gasLimit: '0x1fffffffffffff'
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
  initialContractDeployment:
    enabled: false
    contracts:
      - address: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F"
        bytecode: "53450942895849203584032548320548235492305423854923054238594320584329543205843902865029568459348205849230583428549328053428"
  blockchain:
    nodes:
      generate: true
      count: 4
    accountPassword: 'password'
