#helm install genesis -f values/noproxy-and-novault/genesis-sec.yaml -n carrier-bes besu-genesis
global:
  serviceAccountName: bevel-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: kubernetes
    network: besu

settings:
  # Flag to ensure the genesis configmap is removed on helm uninstall
  removeGenesisOnDelete: true
  # Flag to copy genesis and static nodes from files for secondary members
  secondaryGenesis: true
