---
#helm install member-1 -f values/noproxy-and-novault/txnode.yml -n besu besu-node 
#helm upgrade member-1 -f values/noproxy-and-novault/txnode.yml -n besu besu-node
global:
  serviceAccountName: bevel-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: kubernetes
  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local

storage:
  size: "2Gi"
tessera:
  enabled: true
  tessera:
    tlsMode: "OFF"
  resources:
    cpuLimit: 1
    cpuRequest: 0.5
    memLimit: "2G"
    memRequest: "1G"
    password: 'password'
  storage:
    enabled: false
    size: 1Gi
    dbSize: 2Gi
    allowedTopologies:
      enabled: false
  
  tls:
    enabled: false
    settings:
      certSubject: CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB
      tmTls: true

node:
  removeKeysOnDelete: false # this will erase keys - so be careful with this on validators
  isBootnode: false    # set this to true if this node is a bootnode
  usesBootnodes: false
  besu:
    envBesuOpts: ""  
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 1
      cpuRequest: 0.5
      memLimit: "2G"
      memRequest: "1G"
    account:
      password: 'password'
