##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: '0.15.0'
description: "Hyperledger Besu: Generates and stores TLS certificates for nodes and tessera"
name: besu-tlscert-cert-gen
version: '0.15.0'
appVersion: latest
dependencies:
  - name: bevel-vault-mgmt
    alias: bevel-vault-mgmt
    repository: https://hyperledger.github.io/bevel
    tags:
      - bevel
    version: 0.15.0
  - name: bevel-scripts
    alias: bevel-scripts
    repository: https://hyperledger.github.io/bevel
    tags:
      - bevel
    version: 0.15.0
