##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v1
name: besu-node
description: Hyperledger Besu nodes for a POA network
version: 0.15.0
appVersion: latest
dependencies:
  - name: bevel-storageclass
    alias: storage
    repository: "file://../../../shared/charts/bevel-storageclass"
    tags:
      - bevel
    version: ~0.15.0
    condition: storage.enabled
  - name: besu-tlscert-gen
    alias: tls
    repository: "file://../besu-tlscert-gen"
    tags:
      - bevel
    version: ~0.15.2
    condition: tls.enabled
  - name: besu-tessera-node
    alias: privacy
    repository: "file://../besu-tessera-node"
    tags:
      - bevel
    version: ~0.15.0
    condition: privacy.enabled
keywords:
  - bevel
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
