dependencies:
  - name: bevel-storageclass
    alias: storage
    repository: "file://../../../shared/charts/bevel-storageclass"
    tags:
      - storage
    version: ~1.0.0
  - name: besu-tessera-node
    alias: tessera
    repository: "file://../besu-tessera-node"
    tags:
      - tessera
    version: ~1.1.0
    condition: tessera.enabled
  - name: besu-tlscert-gen
    alias: tls
    repository: "file://../besu-tlscert-gen"
    tags:
      - bevel
    version: ~1.1.0
    condition: tls.enabled
