##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: A Helm3 chart for generating certificates and keys required by Tessera transaction manager
name: tessera_key_mgmt
version: '0.14.1'
