##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v2
appVersion: "0.2.3"
description: "Shared: Bevel Image Automation using Flux V2"
name: bevel-image-automation
version: 0.15.1
