---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeName }}-internal
  namespace: {{ .Values.metadata.namespace}}
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.nodeName }}
# we need healthCheckNodePort set to get rid of logs pollution
{{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
{{- end }}  
  ports:
  - name: bridge-tunnel
    protocol: TCP
    port: {{ .Values.bridge.tunnelPort }}
    targetPort: {{ .Values.bridge.tunnelPort }}
