# This role fetches the credentials from the network.yaml and pushes them to the vault of corresponding organizations

# Check if the keystore credentials are already present in the vault
- name: Check if the keystore credentials are already present in the vault
  shell: |
    vault read secret/{{ org.name | lower }}/credentials/keystore
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  register: vault_credentials_keystore
  ignore_errors: yes

# Write the keystore credentials to the vault
- name: Write the keystore credentials to the vault if they dont exist
  shell: |
    vault write secret/{{ org.name | lower }}/credentials/keystore idman={{ org.credentials.keystore.idman }} networkmap={{ org.credentials.keystore.networkmap }} subordinateca={{ org.credentials.keystore.subordinateca }} rootca={{ org.credentials.keystore.rootca }} tlscrlsigner={{ org.credentials.keystore.tlscrlsigner }} keyStorePassword={{ org.credentials.keystore.keystore }}
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  when: vault_credentials_keystore.failed == True

# Check if the truststore credentials are already present in the vault
- name: Check if the truststore credentials are already present in the vault
  shell: |
    vault read secret/{{ org.name | lower }}/credentials/truststore
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  register: vault_credentials_truststore
  ignore_errors: yes

# Write the truststore credentials to the vault
- name: Write the truststore credentials to the vault if they dont exist
  shell: |
    vault write secret/{{ org.name | lower }}/credentials/truststore rootca={{ org.credentials.truststore.rootca }} ssl={{ org.credentials.truststore.ssl }} trustStorePassword={{ org.credentials.truststore.truststore }}
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  when: vault_credentials_truststore.failed == True

# Check if the ssl credentials are already present in the vault
- name: Check if the ssl credentials are already present in the vault
  shell: |
    vault read secret/{{ org.name | lower }}/credentials/ssl
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  register: vault_credentials_ssl
  ignore_errors: yes

# Write the ssl credentials to the vault
- name: Write the ssl credentials to the vault if they dont exist
  shell: |
    vault write secret/{{ org.name | lower }}/credentials/ssl idman={{ org.credentials.ssl.idman }} networkmap={{ org.credentials.ssl.networkmap }} signer={{ org.credentials.ssl.signer }} root={{ org.credentials.ssl.root }}
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  when: vault_credentials_ssl.failed == True
