# Check if the node credentials are present in the vault
- name: Check if the ssl credentials are already present in the vault
  shell: |
    vault read secret/{{ org.name | lower }}/{{ peer.name | lower }}/credentials/root
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  register: vault_credentials_node
  ignore_errors: yes

# Write the networkroot truststore password, node truststore password and node keystore password to the vault
- name: Write networkroottruststore, node truststore, node keystore password to the vault
  shell: |
    vault write secret/{{ org.name | lower }}/{{ peer.name | lower }}/credentials/root truststore={{ network | json_query('orderers[?type==`networkmap`].truststore_pass') | first }}
    vault write secret/{{ org.name | lower }}/{{ peer.name | lower }}/credentials/truststore node={{ peer.credentials.truststore.node }}
    vault write secret/{{ org.name | lower }}/{{ peer.name | lower }}/credentials/keystore node={{ peer.credentials.keystore.node }}
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  when: vault_credentials_node.failed == True
