# Check if the node credentials are present in the vault
- name: Check if the node credentials are already present in the vault
  shell: |
    vault read {{ org.vault.secret_path | default('secret') }}/{{ org.name | lower }}/{{ peer.name | lower }}/credentials
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  register: vault_credentials_node
  ignore_errors: yes

# Write the networkroot truststore, node truststore, node keystore, firewallca, float and bridge passwords to the vault
- name: Write the networkroot truststore, node truststore, node keystore, firewallca, float and bridge passwords to the vault
  shell: |
    vault write {{ org.vault.secret_path | default('secret') }}/{{ org.name | lower }}/{{ peer.name | lower }}/credentials root={{ network | json_query('network_services[?type==`networkmap`].truststore_pass') | first }} truststore={{ peer.credentials.truststore }} keystore={{ peer.credentials.keystore }} firewallca={{ peer.credentials.firewallca }} float={{ peer.credentials.float }} bridge={{ peer.credentials.bridge }} {{ peer.name }}={{ peer.name }}P
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  when: vault_credentials_node.failed == True

- name: "Write cordapps credentials to vault"
  shell: |
    vault write {{ org.vault.secret_path | default('secret') }}/{{ org.name | lower }}/{{ peer.name | lower }}/credentials root={{ network | json_query('network_services[?type==`networkmap`].truststore_pass') | first }} truststore={{ peer.credentials.truststore }} keystore={{ peer.credentials.keystore }} firewallca={{ peer.credentials.firewallca }} float={{ peer.credentials.float }} bridge={{ peer.credentials.bridge }} {{ peer.name }}={{ peer.name }}P repo_username="{{ org.cordapps.username }}" repo_password="{{ org.cordapps.password }}"
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  when: vault_credentials_node.failed == True and (org.cordapps is defined) and (org.cordapps|length > 0)
