##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for PKI Generator chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#############################################################
#                   Basic Configuration                     #
#############################################################
# Provide the name of the node
# Eg. nodeName: carrier
nodeName: carrier

# This section contains the Corda Node metadata.
metadata:
  # Provide the namespace for the Corda PKI Generator for the node.
  # Eg. namespace: carrier-ent
  namespace: carrier-ent
  # Provide any additional labels for the Corda PKI Generator for the node.
  labels:

# Provide information regarding the Docker images used.
image:
  # Provide the alpine utils image, which is used for all init-containers of deployments/jobs.
  # NOTE: The alpine image used is the base alpine image with CURL installed.
  # Eg. initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
  initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
  # Provide the image for the main pki container.
  # Eg. pkiContainerName: corda/enterprise-pki:1.2-zulu-openjdk8u242
  pkiContainerName: corda/enterprise-pki:1.2-zulu-openjdk8u242
  # Provide the docker-registry secret created and stored in kubernetes cluster as a secret.
  # Eg. imagePullSecret: regcred
  imagePullSecret: ""
  # Pull policy to be used for the Docker image
  # Eg. pullPolicy: Always
  pullPolicy: 

# Required parameter to start any .jar files
# Eg. acceptLicense: YES 
acceptLicense: 

#############################################################
#               HashiCorp Vault Configuration               #
#############################################################
# NOTE: Make sure that the vault is already unsealed, intialized and configured to 
# use Kubernetes service account token based authentication. 
# For more info, see https://www.vaultproject.io/docs/auth/kubernetes

vault:
  # Provide the vault address
  # Eg. address: http://vault.example.com:8200
  address: 
  # Provide the float vault address
  # Eg. address: http://vault.example.com:8200
  floatVaultAddress:
  # Provide the vault role used.
  # Eg. role: vault-role
  role: vault-role
  # Provide the authpath configured to be used.
  # Eg. authpath: cordaentcarrier
  authPath: cordaentcarrier
  # Provide the authpath configured to be used.
  # Eg. authpath: cordaentcarrierfloat
  authpathFloat: cordaentcarrierfloat
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceAccountName: vault-auth
  # Provide the vault path where the certificates are stored
  # Eg. certsecretprefix: secret/carrier/carrier
  certSecretPrefix: secret/carrier/carrier
  # The amount of times to retry fetching from/writing to Vault before giving up.
  # Eg. retries: 10
  retries: 10
  # The amount of time in seconds to wait after an error occurs when fetching from/writing to Vault.
  # Eg. sleepTimeAfterError: 15  
  sleepTimeAfterError: 15

#############################################################
#                  Corda Firewall Details                   #
#############################################################
# This section details the corda firewall subjects

subjects:
  # Mention the subject for the firewallCA
  # Eg. firewallca: "CN=Test Firewall CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
  firewallca: "CN=Test Firewall CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
  # Mention the subject for the float component
  # Eg. float: "CN=Test Float Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
  float:  "CN=Test Firewall CA Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
  # Mention the subject for the bridge component
  # Eg. bridge: "CN=Test Bridge Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"
  bridge: "CN=Test Bridge Certificate, OU=HQ, O=HoldCo LLC, L=New York, C=US"

#############################################################
#                       Settings                            #
#############################################################
volume:
  # Eg. baseDir: /opt/corda
  baseDir: /opt/corda
# Mention the maximum size, in megabytes, of the memory allocation pool
# This is consumed by the pki jar
# Eg. cordaJarMx: 256
cordaJarMx: 256
# Provide the path where the Corda node configuration files are stored
# Eg. configPath: etc
configPath: etc
#Provide the replicacount
# Eg. replicas: 1
replicas: 1
