##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
#                      This role deletes the peer pod so that it restarts                   #       
#############################################################################################

# Delete the given peer
- name: Delete peer pod
  k8s:
    kind: Pod
    name: "{{ pod_name }}"
    namespace: "{{ namespace }}"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes
