##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.metadata.namespace }}
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Values.node.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
    {{- include "labels.custom" . | nindent 2 }}
    {{- if $.Values.labels }}
    {{- range $key, $value := $.Values.labels.deployment }}
    {{- range $k, $v := $value }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
  name: {{ .Values.node.name }}
spec:
  serviceName: {{ .Values.node.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: consortiumchain
      name: {{ .Values.node.name }}
      service.rpc: {{ .Values.node.name }}
      app.kubernetes.io/name: {{ .Values.node.name }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }} 
      {{- if $.Values.labels }}
      {{- range $key, $value := $.Values.labels.deployment }}
      {{- range $k, $v := $value }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
      {{- end }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consortiumchain
        name: {{ .Values.node.name }}
        service.rpc: {{ .Values.node.name }}
        app.kubernetes.io/name: {{ .Values.node.name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }} 
        {{- if $.Values.labels }}
        {{- range $key, $value := $.Values.labels.deployment }}
        {{- range $k, $v := $value }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.vault.serviceaccountname }}
      hostname: {{ .Values.node.name }}.{{ .Values.metadata.namespace }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
          - name: {{ .Values.node.imagePullSecret }}
      volumes:
        - name: certificates
          emptyDir:
            medium: Memory
        - name: {{ .Values.node.name }}-genesis-volume
          configMap:
            name: genesis-{{ .Values.node.name }}
            items:
              - key: genesis.json.base64
                path: genesis.json.base64
        - name: scripts-volume
          configMap:
            name: bevel-vault-script
            defaultMode: 0777
  
      initContainers:
      - name: certificates-init
        image: {{ .Values.images.alpineutils }}
        imagePullPolicy: IfNotPresent
        env:
        - name: VAULT_ADDR
          value: {{ .Values.vault.address }}
        - name: VAULT_SECRET_ENGINE
          value: {{ $.Values.vault.secretengine }}
        - name: VAULT_SECRET_PREFIX
          value: {{ .Values.vault.secretprefix }}
        - name: KUBERNETES_AUTH_PATH
          value: {{ .Values.vault.authpath }}
        - name: VAULT_APP_ROLE
          value: {{ .Values.vault.role }}
        - name: VAULT_TYPE
          value: "{{ $.Values.vault.type }}"
        - name: MOUNT_PATH
          value: "/secret"
        command: ["sh", "-c"]
        args:
        - |-
          #!/usr/bin/env sh

          # Source the bevel-vault.sh script, contains functions to perform the Vault-CURD operations
          . /scripts/bevel-vault.sh

          # Get the Vault token
          echo "Getting the vault Token..."
          vaultBevelFunc 'init'

          # Create a directory if it doesn't already exist
          mkdir -p ${MOUNT_PATH}

          # Obtain the 'key' from the Vault
          vault_secret_key="${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/{{ .Values.vault.keyname }}"
          vaultBevelFunc 'readJson' ${vault_secret_key}

          # Extract 'key' from the response obtained from the Vault and save it to a file
          nodekey=$(echo ${VAULT_SECRET} | jq -r '.["key"]')
          echo "${nodekey}" > ${MOUNT_PATH}/nodekey

          # Check if node TLS is enabled
          if [ {{ $.Values.node.tls }} == "true" ]
          then
            # Obtain TLS-related data from the Vault
            vault_secret_key="${VAULT_SECRET_ENGINE}/${VAULT_SECRET_PREFIX}/{{ .Values.vault.tlsdir }}"
            vaultBevelFunc 'readJson' ${vault_secret_key}

            # Extract 'keystore' and 'password' from the response obtained from the Vault
            keystore=$(echo ${VAULT_SECRET} | jq -r '.["keystore"]')
            keystore_password=$(echo ${VAULT_SECRET} | jq -r '.["password"]' | base64 -d)

            # Save 'keystore' to a file and decode it from base64 to a PKCS12 file.
            echo "${keystore}" > ${MOUNT_PATH}/keystore
            base64 -d ${MOUNT_PATH}/keystore > ${MOUNT_PATH}/keystore.pkcs12

            # Save the keystore password to a file.
            echo "${keystore_password}" > ${MOUNT_PATH}/keystore_password
          fi
        volumeMounts:
        - name: certificates
          mountPath: /secret
        - name: scripts-volume
          mountPath: /scripts/bevel-vault.sh
          subPath: bevel-vault.sh
      - name: liveliness-check
        image: "{{ .Values.images.alpineutils }}"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args:
        - |-
          #!/usr/bin/env sh

          # Check if liveliness check is enabled in the configuration
          {{- if .Values.liveliness_check.enabled }}
              # Initialize a counter variable
              COUNTER=1

              # Start a while loop that runs until the counter reaches the readiness threshold.
              while [ "$COUNTER" -lt {{ $.Values.healthcheck.readinessthreshold }} ]
              do
                  # Get truststore from vault to see if registration is done or not
                  LOOKUP_SECRET_RESPONSE=$(curl -X GET {{ .Values.liveliness_check.url }}:{{ .Values.liveliness_check.port }}/liveness | jq -r 'if .errors then . else . end')
                  
                  # Check if the response from the liveliness check does not contain "UP".
                  if ! echo ${LOOKUP_SECRET_RESPONSE} | grep -E "UP"
                  then
                    # If the check indicates a non-UP state, sleep for the specified readiness check interval.
                    sleep {{ $.Values.healthcheck.readinesscheckinterval }}
                  else
                    # If the check is successful (UP), break out of the loop.
                    break
                  fi

                  # Increment the counter
                  COUNTER=`expr "$COUNTER" + 1`
              done
          {{- end }}
        volumeMounts:
        - name: {{ .Values.node.name }}-pv
          mountPath: {{ .Values.node.mountPath }}
      containers:
      - name: besu
        image: "{{ .Values.images.node }}"
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
        args:
          - | 

            # Create a static-nodes.json file with JSON contents and store it in the specified directory
            echo -n {{ .Values.staticnodes | toJson | quote }} > {{ .Values.node.mountPath }}/static-nodes.json

            # Create a temporary directory for the genesis file
            mkdir -p /tmp/genesis;

            # Decode the Base64-encoded genesis file and save it to the temporary directory
            cat /etc/genesis/genesis.json.base64 | base64 -d > /tmp/genesis/genesis.json

            # Check the consensus type and set the 'args' variable accordingly
            if [ "$CONSENSUS" = "qbft" ]; then
              args="--rpc-http-enabled --rpc-http-api=ETH,NET,QBFT,DEBUG,ADMIN,WEB3 --rpc-ws-enabled --rpc-ws-api=ETH,NET,WEB3 --p2p-port {{ .Values.node.ports.p2p }} --rpc-http-port {{ .Values.node.ports.rpc }} --rpc-ws-port={{ .Values.node.ports.ws }}"
            else
              args="--rpc-http-enabled --rpc-http-api=ETH,NET,IBFT,DEBUG,ADMIN,WEB3 --rpc-ws-enabled --rpc-ws-api=ETH,NET,WEB3 --p2p-port {{ .Values.node.ports.p2p }} --rpc-http-port {{ .Values.node.ports.rpc }} --rpc-ws-port={{ .Values.node.ports.ws }}"
            fi

            # Check if TLS is enabled and set 'tls_args' with TLS-related configuration
            if  {{ $.Values.node.tls }} == "true"
            then
              tls_args="--privacy-tls-enabled --privacy-tls-keystore-file=/secrets/keystore.pkcs12 --privacy-tls-keystore-password-file=/secrets/keystore_password"
            fi

            # Check if metrics are enabled and set 'metrics_args' with metrics-related configuration
            if {{ $.Values.metrics.enabled }} == "true"
            then
              metrics_args="--metrics-enabled --metrics-port={{ template "metrics_port" . }} --metrics-host=0.0.0.0"
            fi

            # Check if onchain-permissioning for the node is enabled and set 'permissioning_args' with permissioning-related configuration.
            if {{ $.Values.node.permissioning.enabled }} == "true"
            then
              permissioning_args="--permissions-accounts-contract-enabled --permissions-accounts-contract-address=0x0000000000000000000000000000000000008888 --permissions-nodes-contract-enabled  --permissions-nodes-contract-address=0x0000000000000000000000000000000000009999 --permissions-nodes-contract-version=2"
              args="--rpc-http-enabled --rpc-http-api=ETH,NET,IBFT,DEBUG,ADMIN,WEB3,PERM --rpc-ws-enabled --rpc-ws-api=ETH,NET,WEB3 --p2p-port {{ .Values.node.ports.p2p }} --rpc-http-port {{ .Values.node.ports.rpc }} --rpc-ws-port={{ .Values.node.ports.ws }}"
            fi

            # Execute the Besu node with the configured options.
            exec /opt/besu/bin/besu \
            --identity={{ .Values.node.name }} \
            --discovery-enabled=false \
            --node-private-key-file=/secrets/nodekey \
            --data-path={{ .Values.node.mountPath }} \
            --genesis-file=/tmp/genesis/genesis.json \
            --logging=DEBUG \
            --nat-method=AUTO \
            --tx-pool-retention-hours=999 \
            --tx-pool-max-size=1024 \
            --p2p-enabled=true \
            --p2p-host=0.0.0.0 \
            --max-peers=25 \
            --host-allowlist="*" \
            --min-gas-price=0 \
            --rpc-http-host=0.0.0.0 \
            --rpc-http-cors-origins="all" \
            --rpc-ws-host=0.0.0.0 \
            --Xdns-enabled=true \
            --Xdns-update-enabled=true \
            $args \
            $tls_args \
            $metrics_args
            $permissioning_args
        ports:
          - name: json-rpc
            containerPort: {{ .Values.node.ports.rpc}}
            protocol: TCP
          - name: ws
            containerPort: {{ .Values.node.ports.ws }}
            protocol: TCP
          - name: rlpx
            containerPort: {{ .Values.node.ports.p2p }}
            protocol: TCP
        env:
          - name: CONSENSUS
            value: "{{ $.Values.node.consensus }}"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: {{ .Values.node.name }}-genesis-volume
          mountPath: /etc/genesis
        - name: certificates
          mountPath: /secrets
          readOnly: true
        - name: {{ .Values.node.name }}-pv
          mountPath: {{ .Values.node.mountPath }}
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.node.name }}-pv
        labels:
          {{- if $.Values.labels }}
          {{- range $key, $value := $.Values.labels.pvc }}
          {{- range $k, $v := $value }}
          {{ $k }}: {{ $v | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
      spec:
        storageClassName: {{ .Values.storage.storageclassname }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage.storagesize }}
