##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "R3-corda-os: Deploys MongoDB, used for doorman and networkmap."
name: corda-mongodb
version: '0.15.0'
