##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Provide the Name for node to be deployed
#Eg. nodeName: mongodb-doorman
nodeName: mongodb
replicas: 
image: 
  #Provide the name of image for container
  #Eg. containerName: hyperledgerlabs/h2:2018
  containerName: hyperledgerlabs/h2:2018
storage:
  #Provide the memory for node
  #Eg. memory: 4Gi
  memory: 4Gi
  name: 
  mountPath: 
service:
  #Provide the type of service
  #Eg. type: NodePort
  type: NodePort
  tcp:
    #Provide the tcp port for node 
    #Eg. port: 9101
    port: 9101
    #Provide the tcp node port for node 
    #Eg. port: 32001
    nodePort: 
    #Provide the tcp node port for node 
    #Eg. targetPort: 27017
    targetPort: 27017
