# This role calls for ambassador certificate creation for each node.
---
- name: Create Ambassador certificates
  include_tasks: nested_main.yaml
  vars:
    node_name: "{{ peer.name | lower }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
