##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

############################################################################################
# This task initiates the nested join channel role to internally join the peers in various permutations

# Check or wait for the create channel job to complete
- name: "waiting for {{ participant.name }} to create channel {{ channel_name }}"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: "Job"
    namespace: "{{ participant.name | lower}}-net"
    component_name: "createchannel-{{ channel_name }}"
    kubernetes: "{{ org.k8s }}"
  when:
    - participant.type == 'creator' and ('2.2.' in network.version or '1.4.' in network.version)
    - participant.org_status is not defined or participant.org_status == 'new'

# Create the join channel value file for each participating peer
- name: "join channel {{ channel_name }}"
  include_role:
    name: helm_component
  vars:
    name: "{{ participant.name }}"
    type: "join_channel_job"    
    component_name: "join-{{ channel_name }}-{{ participant.name }}-{{ peer.name }}"
    peer_name: "{{ peer.name }}"
    component_ns: "{{ participant.name | lower}}-net"
    git_protocol: "{{ org.gitops.git_protocol }}"
    git_url: "{{ org.gitops.git_url }}"
    git_branch: "{{ org.gitops.branch }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    vault: "{{ org.vault }}"
    k8s: "{{ org.k8s }}"
    values_dir: "{{playbook_dir}}/../../../{{org.gitops.release_dir}}/{{ org.name | lower }}"
  loop: "{{ participant.peers }}"
  loop_control:
    loop_var: peer
  when: peer.peerstatus is not defined or peer.peerstatus == 'new'

# Git Push : Push the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ org.gitops }}"
    msg: "[ci skip] Pushing channel-join files"
