##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Hyperledger Fabric: Deploys a CA server."
name: fabric-ca-server
version: '0.15.0'
