##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Create keys for each node
- name: Create keys for each node
  include_tasks: nested_main.yaml
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
