##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role deletes the Vault configurations
#############################################################################################

# Delete the Docker credentials
- name: Delete docker creds
  k8s:
    kind: Secret
    namespace: "{{ component_name }}"
    name: "regcred"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: true
  changed_when: false

# Delete crypto materials from vault
- name: Delete Crypto for nodes
  shell: |
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{ org_name }}/{{ org_name }}-{{ org.type }}-certs
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{ org_name }}/{{ org_name }}-{{ org.type }}-registrationcerts
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{ org_name }}/{{ org_name }}-{{ org.type }}-tlscerts
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: peer
  when: services.peers is defined
  ignore_errors: true

- name: Delete Crypto for notary
  shell: |
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{ org_name }}/{{ org_name }}-{{ org.type }}-certs
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{ org_name }}/{{ org_name }}-{{ org.type }}-registrationcerts
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{{ org_name }}/{{ org_name }}-{{ org.type }}-tlscerts
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  vars: 
    peer: "{{ services.notary }}"
  when: services.notary is defined
  ignore_errors: true

- name: Delete Crypto for network service
  shell: |
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{ org_name }}/{{ org_name }}-{{ org.type }}-certs
    vault kv delete {{ org.vault.secret_path | default('secretsv2') }}/{{ org_name }}/{{ org_name }}-{{ org.type }}-tlscerts
  environment:
    VAULT_ADDR: "{{ org.vault.url }}"
    VAULT_TOKEN: "{{ org.vault.root_token }}"
  ignore_errors: true
  when: component_type == 'node'
