##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Release.Name }}-svc
  annotations:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-svc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
    {{- include "labels.custom" . | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    name: {{ .Release.Name }}-cactus-connector
{{- if eq $.Values.proxy.provider "ambassador" }}
## Mapping for connector port
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ .Release.Name }}-svc-mapping
  namespace: {{ .Values.metadata.namespace }}
spec:
  hostname: '{{ .Values.plugins.besuNode }}.{{ .Values.proxy.external_url }}'
  prefix: /
  service: http://{{ .Release.Name }}-svc.{{ .Values.metadata.namespace }}:{{ .Values.service.port }}
{{- end }}
