##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Register a temporary directory
- name: Register temporary directory
  tempfile:
    state: directory
  register: tmp_directory
  changed_when: false

# Check if go is already installed or not
- name: Check go
  stat:
    path: "{{ go_root_dir }}/go"
  register: go_stat_result
  changed_when: false

# Download golang tar 
- name: Download golang tar 
  get_url:
    url: "https://storage.googleapis.com/golang/go{{ go.version }}.{{ install_os }}-{{ install_arch }}.tar.gz"
    dest: "{{ tmp_directory.path }}"
    mode: 0440
  when: not go_stat_result.stat.exists

# Create bin directory
- name: Create bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
  when: not go_stat_result.stat.exists

# Extract the Go tarball
- name: Extract the Go tarball
  unarchive:
    src: "{{ tmp_directory.path }}/go{{ go.version }}.{{install_os}}-{{install_arch}}.tar.gz"
    dest: "{{ go_root_dir }}"
    copy: no
  become: yes  
  when: not go_stat_result.stat.exists

# Test go installation
- name: Test go installation
  command: "go version"
  changed_when: false
  environment:
    GOROOT: "{{ go_root_dir }}"
