#############################################################################################
# This role creates the block modification script.
#############################################################################################
############################################################################################
# This task calls nested_create_appchannel_block for the orderer organization
- name: Call nested_create_appchannel_block for each orderer
  include_tasks: nested_create_appchannel_block.yaml
  vars:
    orderers: "{{ org.services.orderers }}"
  loop: "{{ network.organizations }}"
  loop_control:
    loop_var: org
  when: org.type == 'orderer'
