##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Delete follower channel
- name: Delete follower channel
  k8s:
    kind: "FabricFollowerChannel"
    api_version: "hlf.kungfusoftware.es/v1alpha1"
    name: "{{ channel_name }}-{{ org_name }}"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes

# Delete main channel
- name: Delete main channel
  k8s:
    kind: "FabricMainChannel"
    api_version: "hlf.kungfusoftware.es/v1alpha1"
    name: "{{ channel_name }}"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes
