##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
# Besu binary version
appVersion: '21.10.6'
description: A Helm chart to perform node key generation
name: node_key_mgmt
version: '0.14.0'
