##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for node-key-mgmt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: 
  namespace:
  #Provide the name for node-key-mgmt release
  #Eg. name: node-key-mgmt
  name:

image:
  #Provide the image repository for the besu container
  #Eg. repository: hyperledger/besu:latest
  besucontainer:
  #Provide the image repository for the besu container
  #Eg. repository: ghcr.io/hyperledger/bevel-alpine:latest
  alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  pullSecret: regcred
  #Provide the image pull policy of image
  #Eg. pullSecret: IfNotPresent
  pullPolicy: IfNotPresent

vault:
  #Provide the vault server address
  #Eg. address: http://54.226.163.39:8200
  address:
  #Provide the vault secret engine name
  #Eg. secretengine: secretsv2
  secretengine:
  #Provide the key path for vault
  #Eg. authpath: besu.carrier
  authpath: 
  #Provide the identity for vault
  #Eg. role: my-identity
  role: vault-role
  # Provide the service account name autheticated to vault.
  # NOTE: Make sure that the service account is already created and autheticated to use the vault.
  # Eg. serviceAccountName: vault-auth
  serviceaccountname: vault-auth

organisation:
  #Provide list of nodes names as k/v pair
  #Eg. - name: validator1
  nodes:

labels:
  service: []
  pvc: []
  deployment: []
healthcheck:
  sleepTimeAfterError: 6
  retries: 10
