##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "R3-corda-ent: Job for initial notary node registration."
name: corda-ent-notary-initial-registration
version: '0.15.0'
