apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: salv-orderer60
  namespace: salv-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: salv-orderer60
  chart:
    git: https://github.com/alvaropicazo/blockchain-automation-framework.git
    ref: feature-614
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: salv-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer60
      loglevel: info
      localmspid: salvMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: salvsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: salv-net-auth
      secretprefix: secret/crypto/ordererOrganizations/salv-net/orderers/orderer60.salv-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: hf.dev2.aws.blockchaincloudpoc-develop.com

    genesis: |-
      CiIaINWR96mQ7w0/qaEOXXcGLbf2JLqtw6KgJ0EtQk0Qx82qEsRYCsFYCr5YCngKWggBEAEaBgid
      1fSDBiIKc3lzY2hhbm5lbCpAM2RjYmNkMjA0NTEzYWEwMmEwMjJiMTkzMDVjZDJjMzYyNzYzMWZi
      ZjU0NDE4YzEzNWViOWU0OGNmMjBmNWRkORIaEhipR8mqGbdFJJbOeQEROIWKuMXahG6BcaASwVcK
      vlcSu1cSwy0KB09yZGVyZXISty0S+BcKB3NhbHZNU1AS7BcalBYKA01TUBKMFhKBFhL+FQoHc2Fs
      dk1TUBLLBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDUURDQ0FlV2dBd0lCQWdJSkFM
      eTVMK2tiQjQzak1Bb0dDQ3FHU000OUJBTUNNSUdDTVFzd0NRWURWUVFHCkV3SkhRakVQTUEwR0Ex
      VUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb00KQjA5eVpH
      VnlaWEl4UHpBOUJnTlZCQU1NTm1OaExuTmhiSFl0Ym1WMExtaG1MbVJsZGpJdVlYZHpMbUpzYjJO
      cgpZMmhoYVc1amJHOTFaSEJ2WXkxa1pYWmxiRzl3TG1OdmJUQWVGdzB5TVRBME1Ua3dOalV3TkRs
      YUZ3MHlOREF5Ck1EY3dOalV3TkRsYU1JR0NNUXN3Q1FZRFZRUUdFd0pIUWpFUE1BMEdBMVVFQ0F3
      R1RHOXVaRzl1TVE4d0RRWUQKVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5WlhJ
      eFB6QTlCZ05WQkFNTU5tTmhMbk5oYkhZdApibVYwTG1obUxtUmxkakl1WVhkekxtSnNiMk5yWTJo
      aGFXNWpiRzkxWkhCdll5MWtaWFpsYkc5d0xtTnZiVEJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000
      OUF3RUhBMElBQkNDSGM0clBHdVFFTDNZM2NxRlFmZnZ1NUkyTSs2TVkKY1NpTk11cmNwa01Ld20x
      Y2gzTDNOSGpVSmMxeXQxak9ocXYxQUpuc0VNKzlDZCt6TGp4RWJxaWpRakJBTUE4RwpBMVVkRXdF
      Qi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJSR2xHSWxtNVky
      Ck1lR0JoV0k3ajBEdm5GWVJrekFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBcFRkTXIvVW8zT3Ay
      TFdMdU9ydC8Kc01wQm5xMUFJdksxQTNnV2UrYzRsVDBDSVFDdms2TlpTRmpLeEszd21hRUlldnNy
      dndhYVl5ZDA0d3dvZURhUApqV245anc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLGCC0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDK2pDQ0FxR2dBd0lCQWdJVVhtVXVRYVVvNis2
      R1NVRVhKeGkwVERwaW15WXdDZ1lJS29aSXpqMEVBd0l3CmdZSXhDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWURWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnYKYmpFUU1BNEdBMVVFQ2d3
      SFQzSmtaWEpsY2pFL01EMEdBMVVFQXd3MlkyRXVjMkZzZGkxdVpYUXVhR1l1WkdWMgpNaTVoZDNN
      dVlteHZZMnRqYUdGcGJtTnNiM1ZrY0c5akxXUmxkbVZzYjNBdVkyOXRNQjRYRFRJeE1EUXhPVEEy
      Ck5UUXdNRm9YRFRJeU1EUXhPVEEyTlRrd01Gb3daakVMTUFrR0ExVUVCaE1DUjBJeEd6QVpCZ05W
      QkFjVEVqVXgKTGpVd0x5MHdMakV6TDB4dmJtUnZiakVRTUE0R0ExVUVDaE1IVDNKa1pYSmxjakVQ
      TUEwR0ExVUVDeE1HWTJ4cApaVzUwTVJjd0ZRWURWUVFEREE1QlpHMXBia0J6WVd4MkxXNWxkREJa
      TUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5CkF3RUhBMElBQkhiaXZYRlducWQ0c3p2VlJVSGJVOEJY
      Y3RMeHJDSWFDTm1qcTdkZ3RKeE9xOHVWMVZlOU92QncKdlRHNFBrQ3g3eHQyR0FLajc3alc2dW9R
      aTZGajN0cWpnZ0VPTUlJQkNqQU9CZ05WSFE4QkFmOEVCQU1DQjRBdwpEQVlEVlIwVEFRSC9CQUl3
      QURBZEJnTlZIUTRFRmdRVTFUeEIxaEZmSHd6c2N4VFhPRVRNUHU4aGcva3dId1lEClZSMGpCQmd3
      Rm9BVVJwUmlKWnVXTmpIaGdZVmlPNDlBNzV4V0VaTXdKQVlEVlIwUkJCMHdHNElaWTJFdGRHOXYK
      YkhNdE9EVmlPV0kwTldNNU9TMTRjRFp4Y2pDQmd3WUlLZ01FQlFZSENBRUVkM3NpWVhSMGNuTWlP
      bnNpWVdKaApZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzSW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pCklpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMyRnNk
      aTF1WlhRaUxDSm9aaTVVZVhCbElqb2kKWTJ4cFpXNTBJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FN
      RVFDSUdPajBUUmJqeHJhM3dXbXhiUktKQmNLSHgrKwplUUpTWUlEd3RzY1lCZ1h6QWlCeGtjZEFW
      RnkwQlhNZGVqRTYzVkVhVG02d2tuWDZhNjIwczdIUnh1dk5Ldz09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrLBi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlDUURDQ0FlV2dBd0lCQWdJSkFMeTVMK2tiQjQzak1Bb0dDQ3FHU000OUJBTUNNSUdDTVFzd0NR
      WURWUVFHCkV3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2Iy
      NHhFREFPQmdOVkJBb00KQjA5eVpHVnlaWEl4UHpBOUJnTlZCQU1NTm1OaExuTmhiSFl0Ym1WMExt
      aG1MbVJsZGpJdVlYZHpMbUpzYjJOcgpZMmhoYVc1amJHOTFaSEJ2WXkxa1pYWmxiRzl3TG1OdmJU
      QWVGdzB5TVRBME1Ua3dOalV3TkRsYUZ3MHlOREF5Ck1EY3dOalV3TkRsYU1JR0NNUXN3Q1FZRFZR
      UUdFd0pIUWpFUE1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWUQKVlFRSERBWk1iMjVrYjI0eEVE
      QU9CZ05WQkFvTUIwOXlaR1Z5WlhJeFB6QTlCZ05WQkFNTU5tTmhMbk5oYkhZdApibVYwTG1obUxt
      Umxkakl1WVhkekxtSnNiMk5yWTJoaGFXNWpiRzkxWkhCdll5MWtaWFpsYkc5d0xtTnZiVEJaCk1C
      TUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkNDSGM0clBHdVFFTDNZM2NxRlFmZnZ1NUky
      TSs2TVkKY1NpTk11cmNwa01Ld20xY2gzTDNOSGpVSmMxeXQxak9ocXYxQUpuc0VNKzlDZCt6TGp4
      RWJxaWpRakJBTUE4RwpBMVVkRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0dtTUIw
      R0ExVWREZ1FXQkJSR2xHSWxtNVkyCk1lR0JoV0k3ajBEdm5GWVJrekFLQmdncWhrak9QUVFEQWdO
      SkFEQkdBaUVBcFRkTXIvVW8zT3AyTFdMdU9ydC8Kc01wQm5xMUFJdksxQTNnV2UrYzRsVDBDSVFD
      dms2TlpTRmpLeEszd21hRUlldnNydndhYVl5ZDA0d3dvZURhUApqV245anc9PQotLS0tLUVORCBD
      RVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjEKBkFkbWlucxInEh0IARIZEggSBggBEgIIABoNEgsK
      B3NhbHZNU1AQARoGQWRtaW5zIjQKC0VuZG9yc2VtZW50EiUSGwgBEhcSCBIGCAESAggAGgsSCQoH
      c2Fsdk1TUBoGQWRtaW5zIjAKB1JlYWRlcnMSJRIbCAESFxIIEgYIARICCAAaCxIJCgdzYWx2TVNQ
      GgZBZG1pbnMiMAoHV3JpdGVycxIlEhsIARIXEggSBggBEgIIABoLEgkKB3NhbHZNU1AaBkFkbWlu
      cyoGQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMajhMKDUNvbnNl
      bnN1c1R5cGUS/BIS8RIKCGV0Y2RyYWZ0EuQSCs0SCjRvcmRlcmVyNjAuaGYuZGV2Mi5hd3MuYmxv
      Y2tjaGFpbmNsb3VkcG9jLWRldmVsb3AuY29tEPtBGocJLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0t
      LS0tCk1JSURLakNDQXRDZ0F3SUJBZ0lVV2RyWGFXUjZYT1R6OHZFL3ByZm5lQU9PQml3d0NnWUlL
      b1pJemowRUF3SXcKZ1lJeEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRFZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdgpiakVRTUE0R0ExVUVDZ3dIVDNKa1pYSmxjakUvTUQwR0ExVUVB
      d3cyWTJFdWMyRnNkaTF1WlhRdWFHWXVaR1YyCk1pNWhkM011WW14dlkydGphR0ZwYm1Oc2IzVmtj
      RzlqTFdSbGRtVnNiM0F1WTI5dE1CNFhEVEl4TURReE9UQTIKTlRVd01Gb1hEVEl5TURReE9UQTNN
      REF3TUZvd2FERUxNQWtHQTFVRUJoTUNSMEl4R3pBWkJnTlZCQWNURWpVeApMalV3THkwd0xqRXpM
      MHh2Ym1SdmJqRVFNQTRHQTFVRUNoTUhUM0prWlhKbGNqRU5NQXNHQTFVRUN4TUVjR1ZsCmNqRWJN
      QmtHQTFVRUF4TVNiM0prWlhKbGNqWXdMbk5oYkhZdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtv
      WkkKemowREFRY0RRZ0FFbVhJSkJ2MTJSQzkyVGY2RTZSTW5IbW0xV2hhUzU4TzMrWVdRZzNDbysw
      eEFtdGFOQTZUVQpHcUR3WGttdXRjNUgzM3duL3RGdThqYkFnbmM5WTkyZUxhT0NBVHN3Z2dFM01B
      NEdBMVVkRHdFQi93UUVBd0lECnFEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJR
      VUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWQKQmdOVkhRNEVGZ1FVeG1vTXF6TXRvcTV4T0EwUUhz
      QVU5QzVvd3NVd0h3WURWUjBqQkJnd0ZvQVVScFJpSlp1VwpOakhoZ1lWaU80OUE3NXhXRVpNd1V3
      WURWUjBSQkV3d1NvSVNiM0prWlhKbGNqWXdMbk5oYkhZdGJtVjBnalJ2CmNtUmxjbVZ5TmpBdWFH
      WXVaR1YyTWk1aGQzTXVZbXh2WTJ0amFHRnBibU5zYjNWa2NHOWpMV1JsZG1Wc2IzQXUKWTI5dE1H
      TUdDQ29EQkFVR0J3Z0JCRmQ3SW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3
      aQphR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2liM0prWlhKbGNqWXdMbk5oYkhZdGJtVjBJaXdpYUdZ
      dVZIbHdaU0k2CkluQmxaWElpZlgwd0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFMU3Q0dDNTSCtJ
      QkFXNXdIWldFaTl0cUZ2dTYKL2RiZWh5M2lVNExldzFkUUFpQXZFOHBkVEJKWEtXVTRqc0xJdXNs
      OW1QTml1SjQwYi9kb3RuQjg5RDBXcHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKHCS0t
      LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlES2pDQ0F0Q2dBd0lCQWdJVVdkclhhV1I2WE9U
      ejh2RS9wcmZuZUFPT0Jpd3dDZ1lJS29aSXpqMEVBd0l3CmdZSXhDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWURWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnYKYmpFUU1BNEdBMVVFQ2d3
      SFQzSmtaWEpsY2pFL01EMEdBMVVFQXd3MlkyRXVjMkZzZGkxdVpYUXVhR1l1WkdWMgpNaTVoZDNN
      dVlteHZZMnRqYUdGcGJtTnNiM1ZrY0c5akxXUmxkbVZzYjNBdVkyOXRNQjRYRFRJeE1EUXhPVEEy
      Ck5UVXdNRm9YRFRJeU1EUXhPVEEzTURBd01Gb3dhREVMTUFrR0ExVUVCaE1DUjBJeEd6QVpCZ05W
      QkFjVEVqVXgKTGpVd0x5MHdMakV6TDB4dmJtUnZiakVRTUE0R0ExVUVDaE1IVDNKa1pYSmxjakVO
      TUFzR0ExVUVDeE1FY0dWbApjakViTUJrR0ExVUVBeE1TYjNKa1pYSmxjall3TG5OaGJIWXRibVYw
      TUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdBRW1YSUpCdjEyUkM5MlRmNkU2Uk1u
      SG1tMVdoYVM1OE8zK1lXUWczQ28rMHhBbXRhTkE2VFUKR3FEd1hrbXV0YzVIMzN3bi90RnU4amJB
      Z25jOVk5MmVMYU9DQVRzd2dnRTNNQTRHQTFVZER3RUIvd1FFQXdJRApxREFkQmdOVkhTVUVGakFV
      QmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0RBWURWUjBUQVFIL0JBSXdBREFkCkJnTlZIUTRF
      RmdRVXhtb01xek10b3E1eE9BMFFIc0FVOUM1b3dzVXdId1lEVlIwakJCZ3dGb0FVUnBSaUpadVcK
      TmpIaGdZVmlPNDlBNzV4V0VaTXdVd1lEVlIwUkJFd3dTb0lTYjNKa1pYSmxjall3TG5OaGJIWXRi
      bVYwZ2pSdgpjbVJsY21WeU5qQXVhR1l1WkdWMk1pNWhkM011WW14dlkydGphR0ZwYm1Oc2IzVmtj
      RzlqTFdSbGRtVnNiM0F1ClkyOXRNR01HQ0NvREJBVUdCd2dCQkZkN0ltRjBkSEp6SWpwN0ltaG1M
      a0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2kKYUdZdVJXNXliMnhzYldWdWRFbEVJam9pYjNKa1pYSmxj
      all3TG5OaGJIWXRibVYwSWl3aWFHWXVWSGx3WlNJNgpJbkJsWlhJaWZYMHdDZ1lJS29aSXpqMEVB
      d0lEU0FBd1JRSWhBTFN0NHQzU0grSUJBVzV3SFpXRWk5dHFGdnU2Ci9kYmVoeTNpVTRMZXcxZFFB
      aUF2RThwZFRCSlhLV1U0anNMSXVzbDltUE5pdUo0MGIvZG90bkI4OUQwV3B3PT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRtaW5zGiIKCUJhdGNoU2l6
      ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMa
      HwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIi
      CgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRt
      aW5zEAIaBkFkbWlucyoGQWRtaW5zEpUnCgtDb25zb3J0aXVtcxKFJxK6JgoVU3VwcGx5Q2hhaW5D
      b25zb3J0aXVtEqAmEsIlCgdjYWx2TVNQErYlGt4jCgNNU1AS1iMSyyMSyCMKB2NhbHZNU1ASywYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ1FEQ0NBZVdnQXdJQkFnSUpBS3RJUDl6WHhT
      cTdNQW9HQ0NxR1NNNDlCQU1DTUlHQ01Rc3dDUVlEVlFRRwpFd0pIUWpFUE1BMEdBMVVFQ0F3R1RH
      OXVaRzl1TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NCkIwTmhjbkpwWlhJeFB6
      QTlCZ05WQkFNTU5tTmhMbU5oYkhZdGJtVjBMbWhtTG1SbGRqSXVZWGR6TG1Kc2IyTnIKWTJoaGFX
      NWpiRzkxWkhCdll5MWtaWFpsYkc5d0xtTnZiVEFlRncweU1UQTBNVGt3TmpVeE1ERmFGdzB5TkRB
      eQpNRGN3TmpVeE1ERmFNSUdDTVFzd0NRWURWUVFHRXdKSFFqRVBNQTBHQTFVRUNBd0dURzl1Wkc5
      dU1ROHdEUVlEClZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CME5oY25KcFpYSXhQekE5QmdO
      VkJBTU1ObU5oTG1OaGJIWXQKYm1WMExtaG1MbVJsZGpJdVlYZHpMbUpzYjJOclkyaGhhVzVqYkc5
      MVpIQnZZeTFrWlhabGJHOXdMbU52YlRCWgpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJ
      QUJFeGc3NHB4bjg2MXFEclZHZlRBaXErMXZINVBNb2IzCmFSTG0yMmV6ZHZETVVHWXFMN0t1TjlC
      WjQwclNSMVhHS2tuOEw1SGU3U04vR01yVzNjbUx0bENqUWpCQU1BOEcKQTFVZEV3RUIvd1FGTUFN
      QkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXhJbTVhcjZ0dQp4ZjFWdllS
      U2c5eHVWQUtROERBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTFEUG55b2M4NzZ4VG1FMTZiQnpk
      CkNrNnc3Q2Fua0pFY09vMmNBOWNTTjFNQ0lRRHYzNnN2YjJkaEg5TnBLeDBRc2cxaEhvbzYrb0ls
      dlIxaDhtSkoKeDJucGFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi2wgtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJREN6Q0NBcktnQXdJQkFnSVVCZWNTb0RuMGN3cjJDYmtDWHJ6
      MTNPeXVEREV3Q2dZSUtvWkl6ajBFQXdJdwpnWUl4Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEVlFR
      SURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2CmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21s
      bGNqRS9NRDBHQTFVRUF3dzJZMkV1WTJGc2RpMXVaWFF1YUdZdVpHVjIKTWk1aGQzTXVZbXh2WTJ0
      amFHRnBibU5zYjNWa2NHOWpMV1JsZG1Wc2IzQXVZMjl0TUI0WERUSXhNRFF4T1RBMgpOVFV3TUZv
      WERUSXlNRFF4T1RBM01EQXdNRm93Y3pFTE1Ba0dBMVVFQmhNQ1IwSXhHekFaQmdOVkJBY1RFalV4
      CkxqVXdMeTB3TGpFekwweHZibVJ2YmpFUU1BNEdBMVVFQ2hNSFEyRnljbWxsY2pFY01BMEdBMVVF
      Q3hNR1kyeHAKWlc1ME1Bc0dBMVVFQ3hNRVkyRnNkakVYTUJVR0ExVUVBd3dPUVdSdGFXNUFZMkZz
      ZGkxdVpYUXdXVEFUQmdjcQpoa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVI1b3BldndteDF4UVBs
      VVVmMFBza1ZQeEhHNDNSaWNuK2lMSzFTCkRUbDdoRHVtZE9iQzI1K3dOSmlCOFNHakVwVGRTUWxZ
      aWliREJ5RWZVQW9XNEtYdG80SUJFakNDQVE0d0RnWUQKVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVk
      RXdFQi93UUNNQUF3SFFZRFZSME9CQllFRkZpSnBNUUR1QUtINWtZWApmaFFFb2I4cTFmS0ZNQjhH
      QTFVZEl3UVlNQmFBRkRFaWJscXZxMjdGL1ZXOWhGS0QzRzVVQXBEd01DUUdBMVVkCkVRUWRNQnVD
      R1dOaExYUnZiMnh6TFRnMVlqbGlORFZqT1RrdFpIQm5hamt3Z1ljR0NDb0RCQVVHQndnQkJIdDcK
      SW1GMGRISnpJanA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWlM
      Q0pvWmk1QgpabVpwYkdsaGRHbHZiaUk2SW1OaGJIWWlMQ0pvWmk1RmJuSnZiR3h0Wlc1MFNVUWlP
      aUpCWkcxcGJrQmpZV3gyCkxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKamJHbGxiblFpZlgwd0NnWUlL
      b1pJemowRUF3SURSd0F3UkFJZ2ZFSE0KZWdxVlBFcm1KRXNMSGVVbGs1N1lKMmlmOHJOVHYrK0hB
      Vm1NZ3ZBQ0lGbTJlNlJXZUFaVzY3TnpQNEg4MzdBRApDdmt4R291UlBhRy9SQmx0QUwreQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZKywYtLS0tLUJFR0lOIENFUlRJ
      RklDQVRFLS0tLS0KTUlJQ1FEQ0NBZVdnQXdJQkFnSUpBS3RJUDl6WHhTcTdNQW9HQ0NxR1NNNDlC
      QU1DTUlHQ01Rc3dDUVlEVlFRRwpFd0pIUWpFUE1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURW
      UVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NCkIwTmhjbkpwWlhJeFB6QTlCZ05WQkFNTU5tTmhM
      bU5oYkhZdGJtVjBMbWhtTG1SbGRqSXVZWGR6TG1Kc2IyTnIKWTJoaGFXNWpiRzkxWkhCdll5MWta
      WFpsYkc5d0xtTnZiVEFlRncweU1UQTBNVGt3TmpVeE1ERmFGdzB5TkRBeQpNRGN3TmpVeE1ERmFN
      SUdDTVFzd0NRWURWUVFHRXdKSFFqRVBNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlEClZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CME5oY25KcFpYSXhQekE5QmdOVkJBTU1ObU5oTG1OaGJI
      WXQKYm1WMExtaG1MbVJsZGpJdVlYZHpMbUpzYjJOclkyaGhhVzVqYkc5MVpIQnZZeTFrWlhabGJH
      OXdMbU52YlRCWgpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFeGc3NHB4bjg2MXFE
      clZHZlRBaXErMXZINVBNb2IzCmFSTG0yMmV6ZHZETVVHWXFMN0t1TjlCWjQwclNSMVhHS2tuOEw1
      SGU3U04vR01yVzNjbUx0bENqUWpCQU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFR
      SC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUXhJbTVhcjZ0dQp4ZjFWdllSU2c5eHVWQUtROERBS0Jn
      Z3Foa2pPUFFRREFnTkpBREJHQWlFQTFEUG55b2M4NzZ4VG1FMTZiQnpkCkNrNnc3Q2Fua0pFY09v
      MmNBOWNTTjFNQ0lRRHYzNnN2YjJkaEg5TnBLeDBRc2cxaEhvbzYrb0lsdlIxaDhtSkoKeDJucGFB
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpasg0IARLWBgrLBi0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDUURDQ0FlV2dBd0lCQWdJSkFLdElQOXpYeFNxN01Bb0dDQ3FHU000OUJB
      TUNNSUdDTVFzd0NRWURWUVFHCkV3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZR
      UUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb00KQjBOaGNuSnBaWEl4UHpBOUJnTlZCQU1NTm1OaExt
      TmhiSFl0Ym1WMExtaG1MbVJsZGpJdVlYZHpMbUpzYjJOcgpZMmhoYVc1amJHOTFaSEJ2WXkxa1pY
      WmxiRzl3TG1OdmJUQWVGdzB5TVRBME1Ua3dOalV4TURGYUZ3MHlOREF5Ck1EY3dOalV4TURGYU1J
      R0NNUXN3Q1FZRFZRUUdFd0pIUWpFUE1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWUQKVlFRSERB
      Wk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwTmhjbkpwWlhJeFB6QTlCZ05WQkFNTU5tTmhMbU5oYkhZ
      dApibVYwTG1obUxtUmxkakl1WVhkekxtSnNiMk5yWTJoaGFXNWpiRzkxWkhCdll5MWtaWFpsYkc5
      d0xtTnZiVEJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkV4Zzc0cHhuODYxcURy
      VkdmVEFpcSsxdkg1UE1vYjMKYVJMbTIyZXpkdkRNVUdZcUw3S3VOOUJaNDByU1IxWEdLa244TDVI
      ZTdTTi9HTXJXM2NtTHRsQ2pRakJBTUE4RwpBMVVkRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFI
      L0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJReEltNWFyNnR1CnhmMVZ2WVJTZzl4dVZBS1E4REFLQmdn
      cWhrak9QUVFEQWdOSkFEQkdBaUVBMURQbnlvYzg3NnhUbUUxNmJCemQKQ2s2dzdDYW5rSkVjT28y
      Y0E5Y1NOMU1DSVFEdjM2c3ZiMmRoSDlOcEt4MFFzZzFoSG9vNitvSWx2UjFoOG1KSgp4Mm5wYUE9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChIGY2xpZW50GtQGCssGLS0tLS1CRUdJTiBDRVJU
      SUZJQ0FURS0tLS0tCk1JSUNRRENDQWVXZ0F3SUJBZ0lKQUt0SVA5elh4U3E3TUFvR0NDcUdTTTQ5
      QkFNQ01JR0NNUXN3Q1FZRFZRUUcKRXdKSFFqRVBNQTBHQTFVRUNBd0dURzl1Wkc5dU1ROHdEUVlE
      VlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTQpCME5oY25KcFpYSXhQekE5QmdOVkJBTU1ObU5o
      TG1OaGJIWXRibVYwTG1obUxtUmxkakl1WVhkekxtSnNiMk5yClkyaGhhVzVqYkc5MVpIQnZZeTFr
      WlhabGJHOXdMbU52YlRBZUZ3MHlNVEEwTVRrd05qVXhNREZhRncweU5EQXkKTURjd05qVXhNREZh
      TUlHQ01Rc3dDUVlEVlFRR0V3SkhRakVQTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRApWUVFI
      REFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjBOaGNuSnBaWEl4UHpBOUJnTlZCQU1NTm1OaExtTmhi
      SFl0CmJtVjBMbWhtTG1SbGRqSXVZWGR6TG1Kc2IyTnJZMmhoYVc1amJHOTFaSEJ2WXkxa1pYWmxi
      Rzl3TG1OdmJUQloKTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCRXhnNzRweG44NjFx
      RHJWR2ZUQWlxKzF2SDVQTW9iMwphUkxtMjJlemR2RE1VR1lxTDdLdU45Qlo0MHJTUjFYR0trbjhM
      NUhlN1NOL0dNclczY21MdGxDalFqQkFNQThHCkExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFBB
      UUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlF4SW01YXI2dHUKeGYxVnZZUlNnOXh1VkFLUThEQUtC
      Z2dxaGtqT1BRUURBZ05KQURCR0FpRUExRFBueW9jODc2eFRtRTE2YkJ6ZApDazZ3N0NhbmtKRWNP
      bzJjQTljU04xTUNJUUR2MzZzdmIyZGhIOU5wS3gwUXNnMWhIb282K29JbHZSMWg4bUpKCngybnBh
      QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgRwZWVyGgZBZG1pbnMiMQoGQWRtaW5zEicS
      HQgBEhkSCBIGCAESAggAGg0SCwoHY2Fsdk1TUBABGgZBZG1pbnMiNAoLRW5kb3JzZW1lbnQSJRIb
      CAESFxIIEgYIARICCAAaCxIJCgdjYWx2TVNQGgZBZG1pbnMiMAoHUmVhZGVycxIlEhsIARIXEggS
      BggBEgIIABoLEgkKB2NhbHZNU1AaBkFkbWlucyIwCgdXcml0ZXJzEiUSGwgBEhcSCBIGCAESAggA
      GgsSCQoHY2Fsdk1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicS
      DAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIv
      QWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFk
      bWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGmoKEE9y
      ZGVyZXJBZGRyZXNzZXMSVhI7CjlvcmRlcmVyNjAuaGYuZGV2Mi5hd3MuYmxvY2tjaGFpbmNsb3Vk
      cG9jLWRldmVsb3AuY29tOjg0NDMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxp
      dGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0I
      AxIJCgdSZWFkZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=
