##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
# Tessera verion 
appVersion: '21.7.3'
description: A Helm3 chart for generating Tessera crypto
name: tessera_key_mgmt
version: '0.14.0'
