##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This role push tlscerts to vault for each node
---
# Push tls certificates to vault for nodes
- name: Push tls certificates to vault for nodes
  include_tasks: nested_main.yaml
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: org.type == "node"

# Push tls certificates to vault for notary
- name: Push tls certificates to vault for notary
  include_tasks: nested_notary.yaml
  loop: "{{ org.services.notaries }}"
  loop_control:
    loop_var: peer
  when: org.type == "notary"
