##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
# Besu binary version
appVersion: '21.10.6'
description: "Hyperledger Besu: Generates and stores node cryptographic materials"
name: besu-node-key-mgmt
version: '0.15.0'
