##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "Quorum: This Helm chart deploys an Quorum member (non-validator) node with or without the integration of Tessera transaction manager."
name: quorum-member-node
version: '0.15.0'
