##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v2
name: bevel-scripts
description: "shared: configmaps using scripts"
version: '0.15.0'
appVersion: "1.16.0"
