##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# Default values for vault-script.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# type of platform
network_type:
# namespace for configmap
namespace:
