##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################
#                   Basic Configuration                     #
#############################################################
# Default values for substrate-key-mgmt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The following are for overriding global values
global:
  # Provide the service account name which will be created.
  serviceAccountName: vault-auth
  cluster:
    provider: # choose from: minikube | aws | azure
    cloudNativeServices: false # 'false' is implemented
    #Provide the kubernetes host url
    #Eg. kubernetesUrl: https://10.3.8.5:6443
    kubernetesUrl:
  vault:
    # Provide the type of vault
    type: "hashicorp" # hashicorp | kubernetes
    # Provide the vault role used.
    role: vault-role
    # Provide the network type
    network: substrate
    # Provide the vault server address
    address: "http://vault_url" # "http://inteli-vault.stage.intelipoc.com" # "http://vault_url"
    # Provide the vault authPath configured to be used.
    authPath: oem
    # Provide the secret engine.
    secretEngine: secretsv2
    # Provide the vault path where the secrets will be stored
    secretPrefix: "data/oem"

removeGenesisOnDelete:
  enabled: true
  image:
    repository: ghcr.io/hyperledger/bevel-k8s-hooks
    tag: qgt-0.2.12
    pullPolicy: IfNotPresent

# Provide custom chain name
# Eg. chain: inteli-gcp
chain: inteli

node:
  # Pull substrate Docker image
  image: ghcr.io/inteli-poc/dscp-node
  command: ./dscp-node
  isValidator: false # true | false
  isMember: false    # true | false

tags:
  bevel-vault-mgmt: false # true | false
  bevel-scripts: false    # true | false