##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
name: besu-tlscert-gen
description: "Hyperledger Besu: Generates and stores TLS certificates for nodes and tessera"
version: 0.15.4
appVersion: latest
dependencies:
  - name: bevel-vault-mgmt
    repository: "file://../../../shared/charts/bevel-vault-mgmt"
    tags:
      - bevel
    version: ~0.15.3
    alias: vault
    condition: vault.enabled
  - name: bevel-scripts
    alias: bevel-scripts
    repository: "file://../../../shared/charts/bevel-scripts"
    tags:
      - bevel
    version: ~0.15.1
keywords:
  - bevel
  - hyperledger
  - besu
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
