##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
global:
  serviceAccountName: vault-auth
  vault:
    type: "kubernetes"
  cluster:
    provider: azure
    cloudNativeServices: false
