apiVersion: v1
name: besu-genesis
description: "Hyperledger Besu: Genesis generator"
version: 0.15.0
appVersion: latest
dependencies:
  - name: besu-tlscert-gen
    alias: tls
    repository: "file://../besu-tlscert-gen"
    tags:
      - bevel
    version: 0.15.2
    condition: tls.enabled
keywords:
  - bevel
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
