apiVersion: v1
name: besu-genesis
description: "Hyperledger Besu: Genesis generator"
version: 1.1.0
appVersion: latest
keywords:
  - bevel
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
