dependencies:
  - name: bevel-vault-mgmt
    repository: "https://sownak.github.io/bevel"
    tags:
      - bevel
    version: ~0.15.1
  - name: bevel-scripts
    repository: "https://sownak.github.io/bevel"
    tags:
      - bevel
    version: ~0.15.1