---
global:
  vault:
    enabled: true
    type: hashicorp
    network: besu
    serviceAccountName: vault-auth
    address: test1
    authPath: besunode1
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    role: vault-role
  cluster:
    provider: aws
    cloudNativeServices: false
    kubernetes_url: "test1"
image:
  genesisUtils: consensys/quorum-k8s-hooks:qgt-0.2.12
  alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the secret to use if private repository
  #Eg. pullSecret: regcred
  pullSecret: 
  pullPolicy: IfNotPresent

quorumFlags:
  removeGenesisOnDelete: true

# the raw Genesis config
# rawGenesisConfig.blockchain.nodes set the number of validators/signers
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    gasLimit: '0xf7b760' 
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
    includeQuickStartAccounts: false
  blockchain:
    nodes:
      generate: true
      count: 4
    accountPassword: 'password'
tls:
  enabled: true
  vault:
    enabled: false
  settings:
    tmTls: True
    certSubject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
    externalURL: besunode1.blockchaincloudpoc.com
