##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Create crypto material for each peer with RAFT consensus
- name: Create crypto material for each peer with RAFT consensus
  include_tasks: nested_main.yaml
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
