##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

###################################################################################################
# This role creates the deployment files for indy crypto generate job and pushes them to repository
###################################################################################################

# Wait for namespace creation for stewards
- name: "Wait for namespace creation for stewards"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/k8_component"
  vars:
    component_type: "Namespace"
    component_name: "{{ component_ns }}"
    type: "retry"

# Create image pull secrets
- name: "Create image pull secret for stewards"
  include_role:
    name: create/imagepullsecret

# Generate indy crypto
- name: "Create crypto of stewards, trustee and endorser"
  include_role:
    name: create/helm_component/crypto
  vars:
    component_type: "crypto"
    component_name: "{{ organization }}"
    chartName: "indy-key-mgmt"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}/{{ organization }}"

# Push the created deployment files to repository
- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing deployment files for {{ organization }}"

# Check Vault for correct inserted indy crypto
- name: "Check Vault for Indy crypto"
  include_role:
    name: check/crypto
