##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################


# Check for the crypto material to the vault
- name: Check the crypto material to Vault
  shell: |
    vault kv get -field=privateKey {{ vault.secret_path | default('secretsv2') }}/{{ component_ns }}/crypto/{{ item.name }}/tm
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  with_items: "{{ peers }}"
  register: vault_result
  ignore_errors: yes

# Set a fact based on vault_result
- set_fact:
    generate_crypto_tessera: True
  when: vault_result.failed is defined and vault_result.failed == True
