##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
- name: Set fact for files location
  ansible.builtin.set_fact:
    files_loc: "{{ playbook_dir }}/../../../{{ charts_dir }}/enterprise-node/build/"

- name: Read network-root-truststore.jks content
  ansible.builtin.slurp:
    src: "{{ files_loc }}/network-root-truststore.jks"
  register: network_root_truststore

- name: Read doorman.crt content
  ansible.builtin.slurp:
    src: "{{ files_loc }}/doorman/tls.crt"
  register: doorman_crt

- name: Read nms.crt content
  ansible.builtin.slurp:
    src: "{{ files_loc }}/nms/tls.crt"
  register: nms_crt

- name: Create cenm-certs secret in manufacturer-ent namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cenm-certs
        namespace: "{{ component_ns }}"
      data:
        network-root-truststore.jks: "{{ network_root_truststore.content }}"

- name: Create doorman-tls-certs secret in manufacturer-ent namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: doorman-tls-certs
        namespace: "{{ component_ns }}"
      data:
        tls.crt: "{{ doorman_crt.content }}"

- name: Create nms-tls-certs secret in manufacturer-ent namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: nms-tls-certs
        namespace: "{{ component_ns }}"
      data:
        tls.crt: "{{ nms_crt.content }}"
