##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

##############################################################################################
# This role sets up all Corda node services
##############################################################################################

- name: Get doorman and nms certs
  include_role: 
    name: get/certs
  vars:
    component_ns: "{{ network.organizations[0].name }}-ent"
  # when: network.organizations[0].type=='cenm'

- name: "Setup primary init with network-service org"
  include_role:
    name: setup/init
  vars:
    build_path: "./build"
    init_type: "corda_ent_secondary_init"
    values_dir: "./build/{{ component_ns }}"

# Wait for namespace creation
- name: Gather Kubernetes cluster information
  community.kubernetes.k8s_cluster_info:
    kubeconfig: "{{ kubernetes.config_file }}"
  register: cluster_info

# Set the Kubernetes server URL fact
- name: Set kubernetes_server_url fact
  set_fact:
    kubernetes_server: "{{ cluster_info.connection.host }}"

- name: "Create secrets for node"
  include_tasks: create_secret.yaml

# Create deployment file for notary node
- name: Create notary node deployment file
  include_role: 
    name: helm_component
  vars:    
    type: corda_ent_node
    node_name: "{{ node.name | lower }}"
    p2p_port: "{{ node.ports.p2p }}"
    rpc_port: "{{ node.ports.rpc }}"
    rpc_admin_port: "{{ node.ports.admin_rpc }}"
    subject: "{{ node.subject }}"
    legal_name: "{{ node.subject }}"
    service_name: "{{ node.serviceName }}"
    validating: "{{ node.validating }}"
    nms_url: "{{ network | json_query('network_services[?type==`idman`].uri') | first }}"
    doorman_url: "{{ network | json_query('network_services[?type==`networkmap`].uri') | first }}"
  loop: "{{ node }}"
  loop_control:
    loop_var: node

# Git Push: Push the deployment files for notary node
- name: Push notary deployment files
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing notary deployment file for notary"
