site_name: Hyperledger Bevel
repo_name: hyperledger/bevel
repo_url: https://github.com/hyperledger/bevel
docs_dir: source
site_dir: build
theme:
  name: material
  custom_dir: overrides
  logo: _static/bevel-logo-white.png
  favicon: _static/bevel-icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - content.code.copy
  - content.tabs.link
  - navigation.expand
  - navigation.footer
  - navigation.instant
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - toc.follow
  - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
      - '..'
      - '.'
plugins:
  - search
  - mike
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike
nav:
  - Introduction: index.md
  - Concepts:
    - Sequence Diagram: concepts/sequence-diagram.md
    - Features: concepts/features.md
    - Ansible: concepts/ansible.md
    - Gitops: concepts/gitops.md
    - Helm: concepts/helm.md
    - Kubernetes: concepts/kubernetes.md
    - Vault: concepts/vault.md
  - Getting Started:
    - Pre-requisites: getting-started/prerequisites.md
    - Ansible Contoller: getting-started/prerequisites-machine.md
    - Configure pre-requisites: getting-started/configure-prerequisites.md
    - Running: getting-started/run-bevel.md
  - Tutorials:
    - Tutorial List: tutorials/index.md
    - Developer pre-requisites: tutorials/dev-prereq.md
    - Deploy using Docker: tutorials/docker-deploy.md
    - Deploy using Machine: tutorials/machine-deploy.md
    - Update DNS: tutorials/dns-settings.md
    - Use Bevel with minikube: tutorials/bevel-minikube-setup.md
    - Add a new StorageClass: tutorials/adding-new-storageclass.md
  - Guides:
    - Configuration Files: 
      - Corda Configuration File: guides/networkyaml-corda.md
      - Fabric Configuration File: guides/networkyaml-fabric.md
      - Indy Configuration File: guides/networkyaml-indy.md
      - Quorum Configuration File: guides/networkyaml-quorum.md
      - Besu Configuration File: guides/networkyaml-besu.md
      - Substrate Configuration File: guides/networkyaml-substrate.md
    - Fabric Operations:
      - guides/fabric/add-cli.md
      - guides/fabric/add-new-channel.md
      - guides/fabric/add-new-orderer-org.md
      - guides/fabric/add-new-orderer-peer.md
      - guides/fabric/add-new-org.md
      - guides/fabric/add-new-peer.md
      - guides/fabric/chaincode-operations.md
      - guides/fabric/deploy-fabric-operator.md
      - guides/fabric/deploy-operations-console.md
      - guides/fabric/external-chaincode-operations.md
      - guides/fabric/refresh-user-certs.md
      - guides/fabric/remove-org.md
      - guides/fabric/setup-cactus-connector.md
      - guides/fabric/upgrade-chaincode.md
      - guides/fabric/upgrade-network-1.4.x-2.2.x.md
      - guides/fabric/upgrade-network.md
    - Corda Operations:
      - guides/corda/add-cenm-console.md
      - guides/corda/add-cordapps.md
      - guides/corda/add-new-notary.md
      - guides/corda/add-new-org.md
    - Besu Operations:
      - guides/besu/add-new-member-org.md
      - guides/besu/add-new-validator-node.md
      - guides/besu/add-new-validator-org.md
      - guides/besu/setup-cactus-connector.md
      - guides/besu/setup-onchain-permissioning.md
    - Other Operations:
      - guides/indy-add-new-org.md
      - guides/quorum-add-new-org.md
  - References:
    - Commands: references/commands.md
    - Troubleshooting: references/troubleshooting.md
    - Roadmap: references/roadmap.md
    - Tool Versions: references/tool-versions.md
    - Architecture: references/architecture.md
  - Samples:
    - Supplychain App: samples/supplychain.md
    - Identity App: samples/indy-refapp.md
    - Substrate App: samples/dscp-app.md
  - Contributing:
    - How to Contribute: contributing/how-to-contribute.md
    - Reporting a Bug: contributing/reporting-a-bug.md
    - Requesting a Change: contributing/requesting-a-change.md
    - Asking a Question: contributing/asking-a-question.md
  - FAQs: faqs.md
  - Glossary: glossary.md
