##############################################################################################
#  Copyright Mohit Vaish. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

##############################################################################################
# Updates the channel configuration with modified configuration block
##############################################################################################

# Check for fabric cli
- name: "Check if fabric cli is already present"
  k8s_info:
    kind: Pod
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ org.k8s.config_file }}"
    context: "{{ org.k8s.context }}"
    label_selectors:
      - app = cli
  register: existing_cli

# Create the value file for creater org first peer
- name: "Create valuefile for cli {{ orderer.name }}-{{ org.name }}-{{ channel_name }}"
  include_role:
    name: k8_component
  vars:
    component_type_name: "{{ org.name | lower }}"
    component_type: "orderer_cli_job"
    component_name: "cli-{{ channel_name }}-{{ org.name }}-{{ orderer.name }}"
    orderer_name: "{{ orderer.name }}"
    git_url: "{{ org.gitops.git_url }}"
    git_branch: "{{ org.gitops.branch }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    vault: "{{ org.vault }}"
    channel_name: "{{ channel_name }}"
    storage_class: "{{ org.name | lower }}-{{ org.cloud_provider | lower }}-storageclass"
    release_dir: "{{ build_path }}"
    orderer_component: "{{ orderer.name | lower }}.{{ component_ns }}"
    orderer_address: "{{ orderer.ordererAddress }}"
  when: existing_cli.resources|length == 0

# Start the cli using the value file created in the previous step
- name: "Start cli"
  shell: |
    KUBECONFIG={{ org.k8s.config_file }} helm upgrade --install -f {{ build_path }}/{{ org.name }}/orderer_cli_job.yaml {{ orderer.name }}-{{ org.name }}-cli {{playbook_dir}}/../../../{{org.gitops.chart_source}}/fabric-cli
  when: existing_cli.resources|length == 0

# Waiting for fabric cli to be up
- name: "Waiting for fabric cli to be up"
  k8s_info:
    kind: Pod
    namespace: "{{ component_ns }}"
    kubeconfig: "{{ org.k8s.config_file }}"
    context: "{{ org.k8s.context }}"
    label_selectors:
      - app = cli
  register: get_cli
  until: ("Running" in get_cli|json_query('resources[*].status.phase'))
  retries: "{{ network.env.retry_count }}"
  delay: 40

# Update the configuration block
- name: Update and copy the configuration block from the blockchain
  shell: |
    export PEER_CLI=$(KUBECONFIG={{ org.k8s.config_file }} kubectl get po -n {{ component_ns }} | grep "cli" | head -n 1 | awk '{print $1}')
    KUBECONFIG={{ kubernetes.config_file }} kubectl cp {{ build_path }}/{{ channel_name }}_config_block.pb {{ component_ns }}/${PEER_CLI}:/opt/gopath/src/github.com/hyperledger/fabric/peer/{{ channel_name }}_config_block.pb
    KUBECONFIG={{ kubernetes.config_file }} kubectl exec -n {{ component_ns }} ${PEER_CLI} -- peer channel update -f {{ channel_name }}_config_block.pb -o ${ORDERER_URL} -c {{ channel_name }} --tls --cafile ${ORDERER_CA}
    KUBECONFIG={{ kubernetes.config_file }} kubectl exec -n {{ component_ns }} ${PEER_CLI} -- peer channel fetch config {{ channel_name }}_config_block_latest.pb -o ${ORDERER_URL} -c {{ channel_name }} --tls --cafile ${ORDERER_CA}
    KUBECONFIG={{ kubernetes.config_file }} kubectl cp {{ component_ns }}/${PEER_CLI}:/opt/gopath/src/github.com/hyperledger/fabric/peer/{{ channel_name }}_config_block_latest.pb {{ build_path }}/{{ channel_name }}_config_block.pb
    cat {{ build_path }}/{{ channel_name }}_config_block.pb | base64 > {{ build_path }}/channel-artifacts/{{ channel_name }}.genesis.block.base64
  environment:
    ORDERER_CA: "/opt/gopath/src/github.com/hyperledger/fabric/crypto/orderer/tls/ca.crt"
    ORDERER_URL: "{{ orderer.uri }}"
  vars:
    kubernetes: "{{ org.k8s }}"
