##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "R3-corda-ent: Deploys the idman service."
name: cenm-idman
version: '0.15.0'
