##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: Bevel Chart for vault and kubernetes configuration
name: bevel-vault-mgmt
version: '0.15.0'
