##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v2
name: bevel-vault-mgmt
description: "Shared: Vault and Kubernetes configuration"
version: 0.15.3
appVersion: "latest"
keywords:
  - bevel
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org