##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

global:
  # The name of the ServiceAccount that will be created.
  serviceAccountName: vault-auth
  cluster:
    cloudNativeServices: false # 'false' is implemented, 'true' to use Cloud Native Services (SecretsManager and IAM for AWS) is in future
    #Provide the kubernetes host url
    #Eg. kubernetesUrl: https://10.3.8.5:6443
    kubernetesUrl: 
  vault:
    type: hashicorp # chose from hashicorp | kubernetes
    #Provide the vaultrole for an organization
    #Eg. vaultrole: org1-vault-role
    role: vault-role
    #Provide the vault server address
    #Eg. address: http://vault-884963190.eu-west-1.elb.amazonaws.com:8200
    address:
    #Provide the kubernetes auth backed configured in vault for an organization
    #Eg. authPath: supplychain
    authPath: supplychain
    #Provide the network type for which the policy will be configured
    #Eg. network: besu
    network: besu # choose from: besu | corda | fabric | corda-ent | quorum
    #Provide the vault secret engine name
    #Eg. secretEngine: secretsv2
    secretEngine: secretsv2
    #Provide the value for vault secret prefix. MUST use data
    #Eg. secretPrefix: data/org1
    secretPrefix: "data/supplychain"
    #Kuberenetes secret for vault ca.cert
    #Enable or disable TLS for vault communication if value present or not
    #Eg. tls: vaultca
    tls:

image:
  #Provide the valid image name and version to read certificates from vault server
  #Eg.repository: ghcr.io/hyperledger/bevel-alpine:latest
  repository: ghcr.io/hyperledger/bevel-alpine
  tag: latest
  #Provide the pullSecret for vault
  #Eg. pullSecret: regcred
  pullSecret: ""

#Provide the custom labels
#NOTE: Provide labels other than name, release name , release service, chart version , chart name , app.
#Eg. labels:
#      role: anchorpeer
labels:
