##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: org1-net
  namespace: org1-net 
  #Provide Fabric version
  #Eg. version: 2.5.4
  network:
    version: 2.5.4
  images:
    #Provide the valid image name and version for fabric tools
    #Eg. fabrictools: hyperledger/fabric-tools:2.2.2
    fabrictools: ghcr.io/hyperledger/bevel-fabric-tools:2.5.4
    #Provide the valid image name and version to read certificates from vault server
    #Eg. alpineutils: hyperledgerlabs/alpine-utils:1.0
    alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the custom labels
  #NOTE: Provide labels other than name, release name , release service, chart version , chart name , app.
  #Eg. labels:
  #      role: create_channel
  labels:

deployment:
  annotations:

vault:
  #Provide the vaultrole for an organization
  #Eg. vaultrole: vault-role
  role: vault-role
  #Provide the vault server address
  #Eg. vaultaddress: http://vault.internal.example.com:9000
  address: 
  #Provide the kubernetes auth backed configured in vault for an organization
  #Eg. authpath: devorg1-net-auth
  authpath: devorg1-net-auth
  #Provide the value for vault secretprefix
  #Provide the value for vault secretprefix where orderers certificates are stored.
  #Eg. orderersecretprefix: secretsv2/crypto/ordererOrganizations/org1-net/orderers
  orderersecretprefix: secretsv2/crypto/ordererOrganizations/org1-net/orderers
  #Provide the serviceaccountname for vault
  #Eg. serviceaccountname: vault-auth
  serviceaccountname: vault-auth
  #Provide the type of vault
  #Eg. type: hashicorp
  type: hashicorp
  #Provide the imagesecretname for vault
  #Eg. imagesecretname: regcred
  imagesecretname: ""

channel:
  #Provide the name of the channel
  #Eg. name: mychannel
  name: mychannel

orderer:
  #Provide orderer's names
  #Eg. address: orderer1*orderer2*orderer3
  orderer_info: orderer1

#Provide the base64 encoded genesis file 
genesis:
