##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "R3-corda-ent: Deploys the bridge component of the Corda Enterprise Firewall."
name: corda-ent-bridge
version: '0.15.0'
