---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  {{- if .Values.nodeConf.deployment.annotations }}
  annotations:
{{ toYaml .Values.nodeConf.deployment.annotations | indent 8 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nodeName }}
      app.kubernetes.io/name: {{ .Values.nodeName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodeName }}
        app.kubernetes.io/name: {{ .Values.nodeName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ $.Values.vault.serviceAccountName }}
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-check-registration
        image: {{ .Values.image.initContainerName }}
        imagePullPolicy: Always
        env:
          - name: VAULT_ADDR
            value: {{ $.Values.vault.address }}
          - name: VAULT_APP_ROLE
            value: {{.Values.vault.role}}
          - name: KUBERNETES_AUTH_PATH
            value: {{ $.Values.vault.authPath }}
          - name: CERTS_SECRET_PREFIX
            value: {{ .Values.vault.certSecretPrefix }}
        command: ["sh", "-c"]
        args:
        - |-
            #!/usr/bin/env sh
              validateVaultResponse () {
                if echo ${2} | grep "errors"; then
                  echo "ERROR: unable to retrieve ${1}: ${2}"
                  exit 1
                fi
              }

            # setting up env to get secrets from vault
            echo "Getting secrets from Vault Server"
            KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
            validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
            echo "logged into vault"
            COUNTER=1
            while [ "$COUNTER" -lt {{ $.Values.vault.retries }} ]
            do
                # get truststore from vault to see if registration is done or not
                LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs/truststore | jq -r 'if .errors then . else . end')
                if echo ${LOOKUP_SECRET_RESPONSE} | grep "errors"
                then
                  sleep {{ $.Values.vault.retryInterval }}
                else
                  break
                fi 
                COUNTER=`expr "$COUNTER" + 1`
            done

            if [ "$COUNTER" -ge {{ $.Values.vault.retries }} ]
            then
              # printing number of trial done before giving up
              echo "$COUNTER"
              echo "Node registration might not have been done."
              exit 1
            fi
            echo "Done"
      - name: init-certificates
        image: {{ .Values.image.initContainerName }}
        imagePullPolicy: Always
        env:
          - name: VAULT_ADDR
            value: {{ $.Values.vault.address }}
          - name: KUBERNETES_AUTH_PATH
            value: {{ $.Values.vault.authPath }}
          - name: VAULT_APP_ROLE
            value: {{ $.Values.vault.role }}
          - name: BASE_DIR
            value: {{ $.Values.nodeConf.volume.baseDir }}
          - name: CERTS_SECRET_PREFIX
            value: {{ .Values.vault.certSecretPrefix }}
        command: ["sh", "-c"]
        args:
        - |-
              #!/usr/bin/env sh
              validateVaultResponse () {
                if echo ${2} | grep "errors"; then
                  echo "ERROR: unable to retrieve ${1}: ${2}"
                  exit 1
                fi
              }

              # setting up env to get secrets from vault
              echo "Getting secrets from Vault Server"
              KUBE_SA_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
              VAULT_TOKEN=$(curl -sS --request POST ${VAULT_ADDR}/v1/auth/${KUBERNETES_AUTH_PATH}/login -H "Content-Type: application/json" -d '{"role":"'"${VAULT_APP_ROLE}"'","jwt":"'"${KUBE_SA_TOKEN}"'"}' | jq -r 'if .errors then . else .auth.client_token end')
              validateVaultResponse 'vault login token' "${VAULT_TOKEN}"
              OUTPUT_PATH=${BASE_DIR}/certificates              
              # Getting intitial network parameters from Vault

              # get nodekeystore.jks from vault
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs/nodekeystore | jq -r 'if .errors then . else . end')
              validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/nodekeystore)" "${LOOKUP_SECRET_RESPONSE}"
              TLS_NODEKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["nodekeystore.jks"]')
              echo "${TLS_NODEKEYSTORE}" | base64 -d > ${OUTPUT_PATH}/nodekeystore.jks

              # get sslkeystore.jks from vault
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs/sslkeystore | jq -r 'if .errors then . else . end')
              validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/sslkeystore)" "${LOOKUP_SECRET_RESPONSE}"
              TLS_SSLKEYSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["sslkeystore.jks"]')
              echo "${TLS_SSLKEYSTORE}" | base64 -d > ${OUTPUT_PATH}/sslkeystore.jks

              # get truststore.jks from vault
              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ $.Values.nodeName }}/certs/truststore | jq -r 'if .errors then . else . end')
              validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/truststore)" "${LOOKUP_SECRET_RESPONSE}"
              TLS_TRUSTSTORE=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["truststore.jks"]')
              echo "${TLS_TRUSTSTORE}" | base64 -d > ${OUTPUT_PATH}/truststore.jks

              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ .Values.networkServices.idmanName }}/tlscerts | jq -r 'if .errors then . else . end')
              validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/{{ .Values.networkServices.idmanName }}/tlscerts)" "${LOOKUP_SECRET_RESPONSE}"
              IDMAN_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
              echo "${IDMAN_CERT}" | base64 -d > ${OUTPUT_PATH}/idman.crt

              LOOKUP_SECRET_RESPONSE=$(curl -sS --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/${CERTS_SECRET_PREFIX}/{{ .Values.networkServices.networkmapName }}/tlscerts | jq -r 'if .errors then . else . end')
              validateVaultResponse "secret (${CERTS_SECRET_PREFIX}/{{ .Values.networkServices.networkmapName }}/tlscerts)" "${LOOKUP_SECRET_RESPONSE}"
              NETWORKMAP_CERT=$(echo ${LOOKUP_SECRET_RESPONSE} | jq -r '.data["tlscacerts"]')
              echo "${NETWORKMAP_CERT}" | base64 -d > ${OUTPUT_PATH}/networkmap.crt             
              echo "Done fetching all certificates from vault"
        volumeMounts:
        - name: notary-certificates
          mountPath: {{ $.Values.nodeConf.volume.baseDir }}/certificates
      - name: db-healthcheck
        image: {{ .Values.image.initContainerName }}
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args:
        - |-
          #!/usr/bin/env sh
          COUNTER=1
          FLAG=true
          # perform health check if db is up and running before starting corda node
          while [ "$COUNTER" -le {{ $.Values.healthcheck.readinessthreshold }} ]
          do
            DB_NODE={{ .Values.dataSourceProperties.dbUrl }}:{{ .Values.dataSourceProperties.dbPort }}
            STATUS=$(nc -vz $DB_NODE 2>&1 | grep -c open )
            if [ "$STATUS" == 0 ]
            then
              FLAG=false
            else
              FLAG=true
              echo "DB up and running"
            fi
            if [ "$FLAG" == false ]
            then
              echo "Retry attempted $COUNTER times, retrying after {{ $.Values.healthcheck.readinesscheckinterval }} seconds"
              COUNTER=`expr "$COUNTER" + 1`
              sleep {{ $.Values.healthcheck.readinesscheckinterval }}
            else
              echo "SUCCESS!"
              echo "DB up and running!"
              exit 0
              break
            fi
          done
          if [ "$COUNTER" -gt {{ $.Values.healthcheck.readinessthreshold }} ] || [ "$FLAG" == false ]
          then
            echo "Retry attempted $COUNTER times, no DB up and running. Giving up!"
            exit 1
            break
          fi
      containers:
      - name: notary
        image: "{{ .Values.image.nodeContainerName }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ACCEPT_LICENSE
            value: "{{required "You must accept the license agreement to run this software" .Values.acceptLicense }}"
          - name: BASE_DIR
            value: {{ $.Values.nodeConf.volume.baseDir }}
        command: ["/bin/bash", "-c"]
        args:
        - |-
          cp ${BASE_DIR}/etc/*.sh bin/
          chmod +x bin/*

          # to clean network-parameters on every restart
          rm -rf ${BASE_DIR}/network-parameters

          # add idman and networkmap certificates to java keystore
          yes | keytool -importcert -file ${BASE_DIR}/certificates/networkmap.crt -storepass changeit -alias {{ .Values.networkServices.networkMapDomain }} -keystore /usr/lib/jvm/zulu-8-amd64/jre/lib/security/cacerts
          yes | keytool -importcert -file ${BASE_DIR}/certificates/idman.crt -storepass changeit -alias {{ .Values.networkServices.idmanDomain }} -keystore /usr/lib/jvm/zulu-8-amd64/jre/lib/security/cacerts          
          bin/run.sh
        volumeMounts:
        - name: notary-conf
          mountPath: {{ $.Values.nodeConf.volume.baseDir }}/etc
          readOnly: false
        - name: notary-certificates
          mountPath: {{ $.Values.nodeConf.volume.baseDir }}/certificates
          readOnly: false
        - name: notary-volume
          mountPath: {{ $.Values.nodeConf.volume.baseDir }}
          readOnly: false
        resources:
          requests:
            memory: {{ .Values.nodeConf.pod.resources.requests }}
          limits:
            memory: {{ .Values.nodeConf.pod.resources.limits }}
      - name: logs
        image: "{{ .Values.image.nodeContainerName }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ACCEPT_LICENSE
            value: "{{required "You must accept the license agreement to run this software" .Values.acceptLicense }}"
        command: ["/bin/bash", "-c"]
        args:
        - |-
          cd {{ $.Values.nodeConf.volume.baseDir }}/
          while true; do tail -f logs/*.log 2>/dev/null; sleep 5; done
          # in case sth went wrong just wait indefinitely ...
          tail -f /dev/null
        volumeMounts:
        - name: notary-volume
          mountPath: {{ $.Values.nodeConf.volume.baseDir }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecret }}
      volumes:
      - name: notary-conf
        configMap:
          name: {{ .Values.nodeName }}-conf
      - name: notary-certificates
        emptyDir:
          medium: Memory
      - name: notary-volume
        persistentVolumeClaim:
          claimName: {{ .Values.nodeName }}-volume
