##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "2.0"
description: "R3-corda-ent: Deploys H2 DB."
name: corda-ent-h2
version: '0.15.0'
