##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for nodechart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Provide the Name for node to be deployed
#Eg. nodeName: notary
nodeName: notary

deployment:
  annotations: {}

# This section contains the db metadata.
metadata:
  # Provide the namespace for the Corda node.
  # Eg. namespace: cenm
  namespace: cenm

# Provide the number of replicas for your pods
# Eg. replicaCount: 1
replicaCount:

image:
  #Provide the name of image for container
  #Eg. containerName: hyperledgerlabs/h2:2018
  containerName: hyperledgerlabs/h2:2018
  #Provide the image pull secret of image
  #Eg. pullSecret: regcred
  imagePullSecret: ""

resources:
  #Provide the limit memory for node
  #Eg. limits: "512Mi"
  limits: "512Mi"
  #Provide the requests memory for node
  #Eg. requests: "512Mi"
  requests: "512Mi"

storage:
  name:
  #Provide the memory for node
  #Eg. memory: 512Mi
  memory: 512Mi
  
pvc:
  annotations: {}

service:
  #Provide the type of service
  #Eg. type: NodePort
  type: NodePort
  tcp:
    #Provide the tcp port for node 
    #Eg. port: 9101
    port: 9101
    #Provide the tcp node port for node 
    #Eg. port: 32001
    nodePort: 
    #Provide the tcp targetPort for node 
    #Eg. targetPort: 1521
    targetPort: 1521
  web:
    #Provide the web node port for node 
    #Eg. port: 32080
    nodePort:  
    #Provide the tcp targetPort for node 
    #Eg. targetPort: 81
    targetPort: 81
    #Provide the tcp node port for node 
    #Eg. port: 8080
    port: 8080
